### ISSUE TITLE
1.16.4 Errors in log file

### ISSUE THREAD

**Issue by thepriz** [CreativeMD/CreativeCore#102]
I saw these errors in the log file. Doesn't seem to hurt anything but thought I should share:

[03Jan2021 20:09:50.349] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: java.io.FileNotFoundException: creativecore:gui/default_style.json
[03Jan2021 20:09:50.349] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraft.resources.FallbackResourceManager.func_199002_a(FallbackResourceManager.java:63)
[03Jan2021 20:09:50.350] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:61)
[03Jan2021 20:09:50.350] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at team.creative.creativecore.common.gui.style.GuiStyle.reload(GuiStyle.java:33)
[03Jan2021 20:09:50.350] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at team.creative.creativecore.client.CreativeCoreClient.init(CreativeCoreClient.java:31)
[03Jan2021 20:09:50.350] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at team.creative.creativecore.CreativeCore.client(CreativeCore.java:44)
[03Jan2021 20:09:50.350] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at team.creative.creativecore.CreativeCore$$Lambda$5804/1474519786.accept(Unknown Source)
[03Jan2021 20:09:50.350] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
[03Jan2021 20:09:50.350] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
[03Jan2021 20:09:50.350] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.eventbus.EventBus$$Lambda$2938/2035258234.invoke(Unknown Source)
[03Jan2021 20:09:50.351] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
[03Jan2021 20:09:50.351] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
[03Jan2021 20:09:50.351] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
[03Jan2021 20:09:50.351] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at net.minecraftforge.fml.ModContainer$$Lambda$3467/1039697154.run(Unknown Source)
[03Jan2021 20:09:50.351] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
[03Jan2021 20:09:50.351] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
[03Jan2021 20:09:50.351] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[03Jan2021 20:09:50.352] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[03Jan2021 20:09:50.352] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
[03Jan2021 20:09:50.352] [Worker-Main-11/INFO] [STDERR/]: [team.creative.creativecore.common.gui.style.GuiStyle:reload:40]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[03Jan2021 20:09:50.352] [Worker-Main-11/ERROR] [creativecore/]: Could not load default style

**Comment by CreativeMD** [comment]
Yeah, it's an unfinished feature. Will be fixed eventually.
