### ISSUE TITLE
crashing upon trying to start a world.

### ISSUE THREAD

**Issue by Masha26th** [CreativeMD/CreativeCore#111]
this is the message I got
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: com.creativemd.creativecore.client.mods.optifine.OptifineHelper.isAntialiasing()Z
Exit Code: -1

and here is the crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.0.1.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre327_mc1.12.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  CreativePatchingLoader (CreativeCore_v1.10.45_mc1.12.2.jar)
  FutureMC (future-mc-1.12.2-0.2.6.1.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 3/17/21 3:31 PM
Description: Unexpected error

java.lang.NoSuchMethodError: com.creativemd.creativecore.client.mods.optifine.OptifineHelper.isAntialiasing()Z
	at com.creativemd.littletiles.client.render.overlay.LittleTilesProfilerOverlay.onRender(LittleTilesProfilerOverlay.java:110)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_657_LittleTilesProfilerOverlay_onRender_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:360)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1123)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.client.render.overlay.LittleTilesProfilerOverlay.onRender(LittleTilesProfilerOverlay.java:110)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_657_LittleTilesProfilerOverlay_onRender_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['creeper26th'/19, l='MpServer', x=-638.50, y=52.00, z=-1386.50, cm:size=1.0000]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-636,4,-1389), Chunk: (at 4,0,3 in -40,-87; contains blocks -640,0,-1392 to -625,255,-1377), Region: (-2,-3; contains chunks -64,-96 to -33,-65, blocks -1024,0,-1536 to -513,255,-1025)
	Level time: 665 game time, 665 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['creeper26th'/19, l='MpServer', x=-638.50, y=52.00, z=-1386.50, cm:size=1.0000]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2166972712 bytes (2066 MB) / 3288334336 bytes (3136 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                                        | Signature                                |
	|:------ |:-------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                  | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy    | 1.0.0                    | minecraft.jar                                 | None                                     |
	| LCHIJA | littletilescore      | 1.0.0                    | minecraft.jar                                 | None                                     |
	| LCHIJA | jei                  | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCHIJA | appleskin            | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	| LCHIJA | quark                | r1.6-179                 | Quark-r1.6-179.jar                            | None                                     |
	| LCHIJA | autoreglib           | 1.3-32                   | AutoRegLib-1.3-32.jar                         | None                                     |
	| LCHIJA | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | blockdrops           | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                   | None                                     |
	| LCHIJA | chiselsandbits       | 14.33                    | chiselsandbits-14.33.jar                      | None                                     |
	| LCHIJA | creativecore         | 1.10.0                   | CreativeCore_v1.10.45_mc1.12.2.jar            | None                                     |
	| LCHIJA | linear               | 1.3                      | linear-1.12.2-1.3.jar                         | None                                     |
	| LCHIJA | littletiles          | 1.5.0                    | LittleTiles_v1.5.0-pre327_mc1.12.2.jar        | None                                     |
	| LCHIJA | buildersbag          | 1.12.2                   | buildersbag-1.12.2-1.4.1.24.jar               | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHIJA | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| LCHIJA | chiseled_me          | 1.12-3.0.0.0-git-7c6a1ba | chiseled-me-1.12-3.0.0.0-git-7c6a1ba.jar      | c677c954974252994736eb15e855e1e6fc5a2e62 |
	| LCHIJA | chromaticfoliage     | 2.1.0                    | ChromaticFoliage-2.1.1.jar                    | None                                     |
	| LCHIJA | clumps               | 3.1.2                    | Clumps-3.1.2.jar                              | None                                     |
	| LCHIJA | customnpcs           | 1.12                     | CustomNPCs_1.12.2-(05Jul20).jar               | None                                     |
	| LCHIJA | effortlessbuilding   | 1.12.2-2.16              | effortlessbuilding-1.12.2-2.16.jar            | None                                     |
	| LCHIJA | fastflyblockbreaking | MC1.9.4-MC1.12.2-1.1     | fastflyblockbreaking-MC1.9.4-MC1.12.2-1.1.jar | None                                     |
	| LCHIJA | fastfurnace          | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                  | None                                     |
	| LCHIJA | forgelin             | 1.8.4                    | Forgelin-1.8.4.jar                            | None                                     |
	| LCHIJA | cfm                  | 6.3.1                    | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| LCHIJA | futuremc             | 0.2.6                    | future-mc-1.12.2-0.2.6.1.jar                  | None                                     |
	| LCHIJA | gardenstuff          | 1.12-2.1.1               | GardenStuff-1.12-2.1.1.jar                    | None                                     |
	| LCHIJA | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA | incontrol            | 3.9.18                   | incontrol-1.12-3.9.18.jar                     | None                                     |
	| LCHIJA | mantle               | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | inspirations         | 1.12.2-0.2.9             | Inspirations-1.12.2-0.2.9.jar                 | None                                     |
	| LCHIJA | itemzoom             | 1.11                     | itemzoom_1.12.2-1.11.jar                      | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCHIJA | kirosblocks          | 1.1                      | kirosblocks-1.1.jar                           | None                                     |
	| LCHIJA | mapgadgets           | @VERSION@                | Mapmaker's+Gadgets-1.2_for_1.12.x.jar         | None                                     |
	| LCHIJA | mightyarchitect      | 0.3.0                    | mightyarchitect-0.3.0.jar                     | None                                     |
	| LCHIJA | moreplayermodels     | 1.12.2                   | MorePlayerModels_1.12.2-(05Dec19).jar         | None                                     |
	| LCHIJA | naturaldecormod      | 1.4.21                   | Natural+Decor+Mod+1.12+II+V1.4.21.jar         | None                                     |
	| LCHIJA | particleculling      | 1.0                      | particleculling-1.12.2-v1.0.1.jar             | None                                     |
	| LCHIJA | pitweaks             | 1.12-1.1.1               | PiTweaks-1.12-1.1.1.jar                       | None                                     |
	| LCHIJA | placebo              | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                      | None                                     |
	| LCHIJA | plants2              | 2.10.7                   | Plants-1.12.2-2.10.7.jar                      | None                                     |
	| LCHIJA | ptrmodellib          | 1.0.4                    | PTRLib-1.0.4.jar                              | None                                     |
	| LCHIJA | randomconfigs        | 1.12.2-1.3.2.3           | randomconfigs-1.12.2-1.3.2.3.jar              | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LCHIJA | sit                  | v1.3                     | sit-1.12.2-v1.3.jar                           | None                                     |
	| LCHIJA | uteamcore            | 2.2.5.147                | u_team_core-1.12.2-2.2.5.147.jar              | None                                     |
	| LCHIJA | variedcommodities    | 1.12.2                   | VariedCommodities_1.12.2(21nov19).jar         | None                                     |
	| LCHIJA | wawla                | 2.6.275                  | Wawla-1.12.2-2.6.275.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | weeeflowers          | 1.12.2b                  | Weee!+Flowers+1.12.2b.jar                     | None                                     |

	Loaded coremods (and transformers): 
ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.0.1.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre327_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.45_mc1.12.2.jar)
  
FutureMC (future-mc-1.12.2-0.2.6.1.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13596 Compatibility Profile Context 20.10.24.01 27.20.1024.1002' Renderer: 'AMD Radeon(TM) Graphics'
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- WailaPlugin (Enabled/Not Forced)

	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) Graphics GL version 4.6.13596 Compatibility Profile Context 20.10.24.01 27.20.1024.1002, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD 3020e with Radeon Graphics 
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13596 Compatibility Profile Context 20.10.24.01 27.20.1024.1002
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by Masha26th** [comment]
nvm i updated creativecore and it fixed it!
