### ISSUE TITLE
hey this is a problem

### ISSUE THREAD

**Issue by ShaneLaw6226** [CreativeMD/CreativeCore#112]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore-1.12.2.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.34_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 3/27/21 4:18 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/creativemd/creativecore/core/CreativeCoreClient
	at com.creativemd.littletiles.client.LittleTilesClient.loadSide(LittleTilesClient.java:252)
	at com.creativemd.littletiles.LittleTiles.registerItems(LittleTiles.java:265)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_5_LittleTiles_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.core.CreativeCoreClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
Caused by: java.lang.NullPointerException

how do i fix it???

**Comment by CreativeMD** [comment]
Please download all of the mods from curseforge and make sure they are up to date.
