### ISSUE TITLE
Crash while starting server

### ISSUE THREAD

**Issue by TheButterbrotMan** [CreativeMD/CreativeCore#138]
https://bytebin.lucko.me/ieJHEwUATL

**Comment by TheButterbrotMan** [comment]
https://github.com/Toadstool-Studios/Playdate/issues/1

**Comment by TheButterbrotMan** [comment]
Without Playdate: https://bytebin.lucko.me/4SUEN98pPL

**Comment by FreezePhoenix** [comment]
@TheButterbrotMan Do you have a link to the website of the dungeonvanilla mod?

**Comment by CreativeMD** [comment]
This issue is not caused by CreativeCore, but `DungeonPlus`. You should report the issue there, because we can't help you.

**Comment by TheButterbrotMan** [comment]
Removing DungeonVanilla mod, is resulting into this log:

https://bytebin.lucko.me/xMHEqzHtyz

**Comment by TheButterbrotMan** [comment]
> Removing DungeonVanilla mod, is resulting into this log:
> 
> https://bytebin.lucko.me/xMHEqzHtyz

So now CreativeCore is the only one appearing in log.

**Comment by FreezePhoenix** [comment]
```
	Suppressed: java.lang.NoSuchMethodError: 'net.minecraft.class_1703 tech.thatgravyboat.playdate.platform.services.IRegistryHelper$ContainerFactory.create(int, net.minecraft.class_1661)'
		at tech.thatgravyboat.fabric.playdate.services.FabricRegistryService.registerContainer(FabricRegistryService.java:96) ~[playdate-2.2.0.jar:?]
		at tech.thatgravyboat.playdate.common.registry.ModContainers.<clinit>(ModContainers.java:11) ~[playdate-2.2.0.jar:?]
		at tech.thatgravyboat.playdate.Playdate.init(Playdate.java:42) ~[playdate-2.2.0.jar:?]
		at tech.thatgravyboat.fabric.playdate.PlaydateFabric.onInitialize(PlaydateFabric.java:20) ~[playdate-2.2.0.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.3.jar:?]
		at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
```
Looks to me like CreativeCore isn't the only one appearing in the error.

**Comment by TheButterbrotMan** [comment]
> ```
> 	Suppressed: java.lang.NoSuchMethodError: 'net.minecraft.class_1703 tech.thatgravyboat.playdate.platform.services.IRegistryHelper$ContainerFactory.create(int, net.minecraft.class_1661)'
> 		at tech.thatgravyboat.fabric.playdate.services.FabricRegistryService.registerContainer(FabricRegistryService.java:96) ~[playdate-2.2.0.jar:?]
> 		at tech.thatgravyboat.playdate.common.registry.ModContainers.<clinit>(ModContainers.java:11) ~[playdate-2.2.0.jar:?]
> 		at tech.thatgravyboat.playdate.Playdate.init(Playdate.java:42) ~[playdate-2.2.0.jar:?]
> 		at tech.thatgravyboat.fabric.playdate.PlaydateFabric.onInitialize(PlaydateFabric.java:20) ~[playdate-2.2.0.jar:?]
> 		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
> 		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
> 		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.3.jar:?]
> 		at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
> 		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
> 		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
> 		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
> 		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
> 		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
> 		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
> 		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
> 		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
> ```
> Looks to me like CreativeCore isn't the only one appearing in the error.

Checkout #139
