### ISSUE TITLE
Creative render thread error

### ISSUE THREAD

**Issue by Patogallina** [CreativeMD/CreativeCore#150]
I have the problem that when opening minecraft it crashes and says
that creativecore could not be run

---- Minecraft Crash Report ----
// My bad.

Time: 2/8/22 14:41
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.1.0-universal.jar%23172!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.1.0-universal.jar%23172!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.19-20220607.102129-srg.jar%23167!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:432) ~[client-1.19-20220607.102129-srg.jar%23167!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:555) ~[client-1.19-20220607.102129-srg.jar%23167!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19-20220607.102129-srg.jar%23167!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19-20220607.102129-srg.jar%23167!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23167!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23167!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23167!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.1.0.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD creativecore --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23169!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23168!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/IModelLoader
		at team.creative.creativecore.CreativeCore.lambda$new$6(CreativeCore.java:99) ~[CreativeCore_FORGE_v2.7.1_mc1.19.jar%23150!/:2.7.1] {re:classloading}
		at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19-41.1.0.jar%23168!/:?] {}
		at team.creative.creativecore.CreativeCore.<init>(CreativeCore.java:99) ~[CreativeCore_FORGE_v2.7.1_mc1.19.jar%23150!/:2.7.1] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23169!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23168!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/Michael/AppData/Roaming/.minecraft/mods/CreativeCore_FORGE_v2.7.1_mc1.19.jar
	Failure message: CreativeCore (creativecore) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 2.7.1
	Mod Issue URL: https://github.com/CreativeMD/CreativeCore/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.model.IModelLoader
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at team.creative.creativecore.CreativeCore.lambda$new$6(CreativeCore.java:99) ~[CreativeCore_FORGE_v2.7.1_mc1.19.jar%23150!/:2.7.1] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19-41.1.0.jar%23168!/:?] {}
	at team.creative.creativecore.CreativeCore.<init>(CreativeCore.java:99) ~[CreativeCore_FORGE_v2.7.1_mc1.19.jar%23150!/:2.7.1] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23169!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23168!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 258984336 bytes (246 MiB) / 570425344 bytes (544 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2,50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1f15
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1278
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 2,40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 3,20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 16087,19
	Virtual memory used (MB): 14173,85
	Swap memory total (MB): 3960,13
	Swap memory used (MB): 237,51
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
		kotlinforforge@3.5.0
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		SereneSeasons-1.19-8.0.0.19.jar                   |Serene Seasons                |sereneseasons                 |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		entityculling-forge-1.5.2-mc1.19.jar              |EntityCulling                 |entityculling                 |1.5.1               |COMMON_SET|Manifest: NOSIGNATURE
		lostcities-1.19-6.0.2.jar                         |LostCities                    |lostcities                    |1.19-6.0.2          |COMMON_SET|Manifest: NOSIGNATURE
		voicechat-forge-1.19-2.2.52.jar                   |Simple Voice Chat             |voicechat                     |1.19-2.2.52         |COMMON_SET|Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.2.0_mc1.19.jar             |Ambient Sounds                |ambientsounds                 |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		BadMobs-1.19-14.1.4.jar                           |BadMobs                       |badmobs                       |14.1.4              |COMMON_SET|Manifest: NOSIGNATURE
		zombiehorsespawn_1.19.0-3.2.jar                   |Zombie Horse Spawn            |zombiehorsespawn              |3.2                 |COMMON_SET|Manifest: NOSIGNATURE
		starterkit_1.19.0-3.4.jar                         |Starter Kit                   |starterkit                    |3.4                 |COMMON_SET|Manifest: NOSIGNATURE
		cgm-1.2.8-1.19.jar                                |MrCrayfish's Gun Mod          |cgm                           |1.2.8               |COMMON_SET|Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.19-1.6.0.jar        |Inventory Profiles Next       |inventoryprofilesnext         |1.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.7.1_mc1.19.jar              |CreativeCore                  |creativecore                  |2.7.1               |ERROR     |Manifest: NOSIGNATURE
		Enhanced_Celestials-forge-1.19-2.0.0.0.jar        |Enhanced Celestials           |enhancedcelestials            |2.0.0.0             |COMMON_SET|Manifest: NOSIGNATURE
		framework-0.3.2-1.19.jar                          |Framework                     |framework                     |0.3.2               |COMMON_SET|Manifest: NOSIGNATURE
		betterfpsdist-1.19-1.5.jar                        |betterfpsdist mod             |betterfpsdist                 |1.19-1.5            |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19-41.1.0-universal.jar                   |Forge                         |forge                         |41.1.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		soundphysics-forge-1.19-1.0.10.jar                |Sound Physics Remastered      |sound_physics_remastered      |1.19-1.0.10         |COMMON_SET|Manifest: NOSIGNATURE
		villagernames_1.19.0-3.7.jar                      |Villager Names                |villagernames                 |3.7                 |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.19.0-4.30.jar                        |Collective                    |collective                    |4.30                |COMMON_SET|Manifest: NOSIGNATURE
		mobsunscreen-3.0.6.jar                            |Mob Sunscreen                 |mobsunscreen                  |3.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		EnhancedVisuals_FORGE_v1.5.6_mc1.19.jar           |EnhancedVisuals               |enhancedvisuals               |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		corpse-1.19-1.0.8.jar                             |Corpse                        |corpse                        |1.19-1.0.8          |COMMON_SET|Manifest: NOSIGNATURE
		[1.19]+SecurityCraft+v1.9.3.jar                   |SecurityCraft                 |securitycraft                 |1.9.3               |COMMON_SET|Manifest: NOSIGNATURE
		TravelersBackpack-1.19-8.0.8.jar                  |Traveler's Backpack           |travelersbackpack             |8.0.8               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 66405f6a-c467-4f77-a1c8-b7a8d5c167db
	FML: 41.1
	Forge: net.minecraftforge:41.1.0

**Comment by CreativeMD** [comment]
Update CreativeCore
