### ISSUE TITLE
Crash after creating a world (SP, MP not tested)

### ISSUE THREAD

**Issue by Esterze** [CreativeMD/CreativeCore#151]
![image](https://user-images.githubusercontent.com/97387354/183050115-1b09b759-9f4f-448a-b0c7-be67c69b3d34.png)

```
[05Aug2022 11:33:04.077] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: 'float team.creative.creativecore.common.util.mc.TickUtils.getDeltaFrameTime(net.minecraft.world.level.Level)'
	Index: 4
	Listeners:
		0: NORMAL
		1: ASM: xaero.map.events.FMLEvents@1aaab87 clientTick(Lnet/minecraftforge/event/TickEvent$ClientTickEvent;)V
		2: ASM: xaero.pvp.events.BPVPFMLEvents@63991c68 handleClientTickEvent(Lnet/minecraftforge/event/TickEvent$ClientTickEvent;)V
		3: ASM: net.minecraftforge.common.ForgeInternalHandler@644e5796 checkSettings(Lnet/minecraftforge/event/TickEvent$ClientTickEvent;)V
		4: net.minecraftforge.eventbus.EventBus$$Lambda$4417/0x0000000100c76248@14922268
		5: ASM: squeek.appleskin.client.HUDOverlayHandler@60cca98c onClientTick(Lnet/minecraftforge/event/TickEvent$ClientTickEvent;)V
		6: ASM: class team.creative.creativecore.client.CreativeCoreClient clientTick(Lnet/minecraftforge/event/TickEvent$ClientTickEvent;)V
		7: net.minecraftforge.eventbus.EventBus$$Lambda$4417/0x0000000100c76248@663b31a
java.lang.NoSuchMethodError: 'float team.creative.creativecore.common.util.mc.TickUtils.getDeltaFrameTime(net.minecraft.world.level.Level)'
	at TRANSFORMER/ambientsounds@0.0NONE/team.creative.ambientsounds.env.TerrainEnviroment.analyzeAirPocket(TerrainEnviroment.java:73)
	at TRANSFORMER/ambientsounds@0.0NONE/team.creative.ambientsounds.env.TerrainEnviroment.analyze(TerrainEnviroment.java:34)
	at TRANSFORMER/ambientsounds@0.0NONE/team.creative.ambientsounds.env.AmbientEnviroment.analyzeSlow(AmbientEnviroment.java:94)
	at TRANSFORMER/ambientsounds@0.0NONE/team.creative.ambientsounds.AmbientTickHandler.onTick(AmbientTickHandler.java:268)
	at TRANSFORMER/creativecore@2.7.4/team.creative.creativecore.CreativeForgeLoader.lambda$registerClientTick$6(CreativeForgeLoader.java:68)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@41.1.0/net.minecraftforge.event.ForgeEventFactory.onPreClientTick(ForgeEventFactory.java:787)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1689)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1047)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.main.Main.main(Main.java:206)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19-41.1.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

[05Aug2022 11:33:04.310] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'float team.creative.creativecore.common.util.mc.TickUtils.getDeltaFrameTime(net.minecraft.world.level.Level)'
	at team.creative.ambientsounds.env.TerrainEnviroment.analyzeAirPocket(TerrainEnviroment.java:73) ~[AmbientSounds_FORGE_v5.2.0_mc1.19.jar%23144!/:?]
	at team.creative.ambientsounds.env.TerrainEnviroment.analyze(TerrainEnviroment.java:34) ~[AmbientSounds_FORGE_v5.2.0_mc1.19.jar%23144!/:?]
	at team.creative.ambientsounds.env.AmbientEnviroment.analyzeSlow(AmbientEnviroment.java:94) ~[AmbientSounds_FORGE_v5.2.0_mc1.19.jar%23144!/:?]
	at team.creative.ambientsounds.AmbientTickHandler.onTick(AmbientTickHandler.java:268) ~[AmbientSounds_FORGE_v5.2.0_mc1.19.jar%23144!/:?]
	at team.creative.creativecore.CreativeForgeLoader.lambda$registerClientTick$6(CreativeForgeLoader.java:68) ~[CreativeCore_FORGE_v2.7.4_mc1.19.jar%23149!/:2.7.4]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPreClientTick(ForgeEventFactory.java:787) ~[forge-1.19-41.1.0-universal.jar%23158!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1689) ~[client-1.19-20220607.102129-srg.jar%23153!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1047) ~[client-1.19-20220607.102129-srg.jar%23153!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23153!/:?]
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23153!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.1.0.jar%2393!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
```

I found that I did not update AS since 30th June, I'll try to create a new world again after updating the mod.

**Comment by Esterze** [comment]
Alright, updating AS to 5.2.1 fixed the issue. I hate how different version of Forge breaks everything up.

**Comment by CreativeMD** [comment]
@Zzeyy will not happen in 1.19.2. It only happens at the beginning of a new version till the first recommend build.
