### ISSUE TITLE
Crash when trying to open certain inventories?

### ISSUE THREAD

**Issue by spoorn** [CreativeMD/CreativeCore#152]
Not exactly sure how to reproduce this.  I think it happened when I tried to open the End Stone Smelter from Better End.  

Minecraft 1.18.2
Fabric Loader 0.14.9
CreativeCore 2.6.12

```
java.lang.NullPointerException: Cannot invoke "team.creative.creativecore.common.gui.IGuiParent.closeTopLayer()" because the return value of "team.creative.creativecore.common.gui.GuiParent.getParent()" is null
    at team.creative.creativecore.common.gui.GuiParent.closeTopLayer(GuiParent.java:290)
    at team.creative.creativecore.common.gui.GuiLayer.keyPressed(GuiLayer.java:124)
    at team.creative.creativecore.common.gui.integration.ScreenEventListener.method_25404(ScreenEventListener.java:105)
    at team.creative.creativecore.common.gui.integration.ContainerScreenIntegration.method_25404(ContainerScreenIntegration.java:62)
    at net.minecraft.class_309.method_1454(class_309.java:384)
    at net.minecraft.class_437.method_25412(class_437.java:492)
    at net.minecraft.class_309.method_1466(class_309.java:380)
    at net.minecraft.class_309.method_22678(class_309.java:472)
    at net.minecraft.class_1255.execute(class_1255.java:103)
    at net.minecraft.class_309.method_22676(class_309.java:472)
    at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
    at org.lwjgl.system.JNI.invokeV(Native Method)
    at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
    at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
    at net.minecraft.class_1041.method_15998(class_1041.java:310)
    at net.minecraft.class_310.method_1523(class_310.java:1147)
    at net.minecraft.class_310.method_1514(class_310.java:737)
    at net.minecraft.client.main.Main.main(Main.java:236)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by CreativeMD** [comment]
Yeah this issue happens, when the gui is closed. Unfortunately I have dropped support for 1.18, but this issue has been fixed in 1.19. It happens if you press the inventory key to close the gui (if I remember it correctly it might also be the ESC key). Very sorry for the issue :|
