### ISSUE TITLE
Error NoSuchMethodError: 'float team.creative.creativecore.common.util.mc.TickUtils.getDeltaFrameTime(net.minecraft.class_1937)'

### ISSUE THREAD

**Issue by lospejos** [CreativeMD/CreativeCore#158]
When using `CreativeCore_FABRIC_v2.8.5_mc1.19.2` with recent `qfapi-4.0.0-beta.11_qsl-3.0.0-beta.15_fapi-0.60.0_mc-1.19.2`, an error occur:

```
java.lang.NoSuchMethodError: 'float team.creative.creativecore.common.util.mc.TickUtils.getDeltaFrameTime(net.minecraft.class_1937)'
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.8)
	at team.creative.ambientsounds.env.TerrainEnviroment.analyzeAirPocket(TerrainEnviroment.java:73)
	at team.creative.ambientsounds.env.TerrainEnviroment.analyze(TerrainEnviroment.java:34)
	at team.creative.ambientsounds.env.AmbientEnviroment.analyzeSlow(AmbientEnviroment.java:94)
	at team.creative.ambientsounds.AmbientTickHandler.onTick(AmbientTickHandler.java:268)
	at team.creative.creativecore.CreativeFabricLoader.lambda$registerClientTick$1(CreativeFabricLoader.java:47)
	at org.quiltmc.qsl.lifecycle.api.client.event.ClientTickEvents.lambda$static$2(ClientTickEvents.java:54)
	at net.minecraft.client.MinecraftClient.handler$ida001$endTick(MinecraftClient:34005)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1907)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1135)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
```

If using previous version `CreativeCore_FABRIC_v2.7.4_mc1.19.1` with the same QFAPI versoin, everything works fine.

Please assist. Thanks!

**Comment by CreativeMD** [comment]
Update AmbientSounds.
