### ISSUE TITLE
There was a severe problem during mod loading that has caused the game to fail (1.12.2)

### ISSUE THREAD

**Issue by prodatastealer** [CreativeMD/CreativeCore#173]
I was trying to load up minecraft when I got this error. 
Here's the crash log: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  ShutdownPatcher (mcef-1.12.2-1.11-coremod.jar)
  LittlePatchingLoader (LittleTiles_v1.5.57_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 3/19/23 6:59 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LittleTiles (littletiles)
Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/common/config/holder/CreativeConfigRegistry
	at com.creativemd.littletiles.LittleTiles.PreInit(LittleTiles.java:250)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.common.config.holder.CreativeConfigRegistry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 436587416 bytes (416 MB) / 2046820352 bytes (1952 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version        | Source                                | Signature                                |
	|:----- |:----------------- |:-------------- |:------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2         | minecraft.jar                         | None                                     |
	| LCH   | mcp               | 9.42           | minecraft.jar                         | None                                     |
	| LCH   | FML               | 8.0.99.99      | forge-1.12.2-14.23.5.2859.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2859   | forge-1.12.2-14.23.5.2859.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy | 1.0.0          | minecraft.jar                         | None                                     |
	| LCH   | littletilescore   | 1.0.0          | minecraft.jar                         | None                                     |
	| LCH   | craftstudioapi    | 1.0.0          | CraftStudio-1.0.0.93-mc1.12-alpha.jar | None                                     |
	| LCH   | creativecore      | 1.9.9          | CreativeCore_v1.9.90_mc1.12.2.jar     | None                                     |
	| LCH   | customnpcs        | 1.12           | CustomNPCs_1.12.2-(05Jul20).jar       | None                                     |
	| LCH   | ptrmodellib       | 1.0.5          | PTRLib-1.0.5.jar                      | None                                     |
	| LCH   | props             | 2.6.3.7        | Decocraft-2.6.3.7_1.12.2.jar          | None                                     |
	| LCH   | dragonmounts      | 1.12.2-1.6.3   | DragonMounts2-1.12.2-1.6.3.jar        | None                                     |
	| LCH   | cfm               | 5.3.1          | furniture-5.3.1-1.12.2.jar            | None                                     |
	| LCH   | jei               | 4.16.1.301     | jei_1.12.2-4.16.1.301.jar             | None                                     |
	| LCE   | littletiles       | 1.5.0          | LittleTiles_v1.5.57_mc1.12.2.jar      | None                                     |
	| LC    | mca               | 6.1.0          | MCA-1.12.2-6.1.0-universal.jar        | None                                     |
	| LC    | mcef              | 1.11           | mcef-1.12.2-1.11.jar                  | None                                     |
	| LC    | phonesalpha       | v1.11          | pa1.11.jar                            | None                                     |
	| LC    | harvestcraft      | 1.12.2zb       | Pam's+HarvestCraft+1.12.2zg.jar       | None                                     |
	| LC    | radixcore         | 1.12.x-2.2.1   | RadixCore-1.12.x-2.2.1-universal.jar  | None                                     |
	| LC    | roleplayitems     | 1.0.0          | RoleplayThings+1.16.5+(0.2).jar       | None                                     |
	| LC    | kens_rp           | 1.0.3 - 1.14.4 | Updated1.12.2EssentialsRP.jar         | None                                     |
	| LC    | webdisplays       | 1.1            | webdisplays-1.12.2-1.1.jar            | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  
ShutdownPatcher (mcef-1.12.2-1.11-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
LittlePatchingLoader (LittleTiles_v1.5.57_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13596 Compatibility Profile Context 20.10.44.05 27.20.11044.5003' Renderer: 'AMD Radeon(TM) Vega 8 Graphics'

**Comment by prodatastealer** [comment]
The problem was it was outdated, the issue is fixed now
