### ISSUE TITLE
[FORGE] Crash during prelaunch - different mod specified in log every crash

### ISSUE THREAD

**Issue by C8kilc8ac** [CreativeMD/CreativeCore#201]
Minecraft version: 1.20.1
Forge version: 47.1.3, tried several up to latest, chose 47.1.3 for compatibility with most mods I want to use.
Creativecore version: tried 2.11.9 through 2.11.24

I am building a modpack (243 mods) and I cannot figure out this error. Skimmed through the full logs and everything looks normal to my eyes.

```
[10/02/2024 21:20:41 PM] Exception in thread "main" java.lang.module.ResolutionException: Modules creativecore and net.fabricmc.loader export package net.fabricmc.api to module forge
[10/02/2024 21:20:41 PM] 	at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
[10/02/2024 21:20:41 PM] 	at java.base/java.lang.module.Resolver.failTwoSuppliers(Unknown Source)
[10/02/2024 21:20:41 PM] 	at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
[10/02/2024 21:20:41 PM] 	at java.base/java.lang.module.Resolver.finish(Unknown Source)
[10/02/2024 21:20:41 PM] 	at java.base/java.lang.module.Configuration.<init>(Unknown Source)
[10/02/2024 21:20:41 PM] 	at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
[10/02/2024 21:20:41 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
[10/02/2024 21:20:41 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
[10/02/2024 21:20:41 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
[10/02/2024 21:20:41 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
[10/02/2024 21:20:41 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[10/02/2024 21:20:41 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[10/02/2024 21:20:41 PM] 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[10/02/2024 21:20:41 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
```

Without ANY changes, only a restart, the error changes to the following:

```
[10/02/2024 21:32:25 PM] Exception in thread "main" java.lang.module.ResolutionException: Modules net.fabricmc.loader and creativecore export package net.fabricmc.api to module MixinExtras
[10/02/2024 21:32:25 PM] 	at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
[10/02/2024 21:32:25 PM] 	at java.base/java.lang.module.Resolver.failTwoSuppliers(Unknown Source)
[10/02/2024 21:32:25 PM] 	at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
[10/02/2024 21:32:26 PM] 	at java.base/java.lang.module.Resolver.finish(Unknown Source)
[10/02/2024 21:32:26 PM] 	at java.base/java.lang.module.Configuration.<init>(Unknown Source)
[10/02/2024 21:32:26 PM] 	at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
[10/02/2024 21:32:26 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
[10/02/2024 21:32:26 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
[10/02/2024 21:32:26 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
[10/02/2024 21:32:26 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
[10/02/2024 21:32:26 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[10/02/2024 21:32:26 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[10/02/2024 21:32:26 PM] 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[10/02/2024 21:32:26 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
```
On other launches it cycles at random through a long list of dependent mods that I can obviously remove but are not the source of the problem. Please advise.

**Comment by saroiju** [comment]
I'm having the same issue, Anytime i get rid of the other mod creativecore has an issue with, there is another one on 1.20.1 as well

**Comment by CreativeMD** [comment]
You have a few fabric stuff installed, which does not work with CreativeCore. You can fix this issue by opening the CreativeCore mod file and deleting the directory net.fabricmc. Cannot do anything about it.

**Comment by C8kilc8ac** [comment]
I went through the mod list and double checked, confirmed I haven't accidentally downloaded fabric versions of the mods. 
I deleted the directory you specified and that broke everything even more - the logs are riddled with errors relating to creativecore, fabric and lots of other mods.

**Comment by CreativeMD** [comment]
Other mods to the same thing as CreativeCore does. As I commented above the only way to fix it is by deleting the directory inside the CreativeCore mod file (or by removing the conflicting mod of course).
