### ISSUE TITLE
Clients without the mod can't join when opening to LAN

### ISSUE THREAD

**Issue by YoshiRulz** [CreativeMD/CreativeCore#203]
Title. This is relevant to ItemPhysic Lite, though that doesn't need to be installed to repro. Vanilla clients can join fine; only clients *with Fabric API but without CreativeCore* fail to connect, getting a "Received a registry entry..." message instead.

<details>
<summary>relevant part of log</summary>

```
[13:49:40] [Render thread/ERROR]: Received unknown remote registry entries from server
[13:49:40] [Render thread/ERROR]: Registry entry (creativecore:container) is missing from local registry (minecraft:menu)
[13:49:40] [Render thread/ERROR]: Registry remapping failed!
java.util.concurrent.CompletionException: net.fabricmc.fabric.impl.registry.sync.RemapException: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

creativecore

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:146) ~[fabric-registry-sync-v0-4.0.18+78d798af4f-4d8236a4789003c6.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: net.fabricmc.fabric.impl.registry.sync.RemapException: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

creativecore

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.checkRemoteRemap(RegistrySyncManager.java:365) ~[fabric-registry-sync-v0-4.0.18+78d798af4f-4d8236a4789003c6.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:261) ~[fabric-registry-sync-v0-4.0.18+78d798af4f-4d8236a4789003c6.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:143) ~[fabric-registry-sync-v0-4.0.18+78d798af4f-4d8236a4789003c6.jar:?]
	... 14 more
[13:49:41] [Render thread/WARN]: Client disconnected with reason: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

creativecore
```
</details>

**Comment by CreativeMD** [comment]
Sorry but there is nothing I can do about that. The other person has to install CreativeCore as well or you use a dedicated server to host your world.
