### ISSUE TITLE
"Illegal classload request for accessor mixin" spammed in logs

### ISSUE THREAD

**Issue by Sollace** [CreativeMD/CreativeCore#205]
Sometimes it causes the creative screen search tab to break, and sometimes it doesn't. Regardless the error seems to occur any time a save happens.

https://mclo.gs/pRMWZNG

```
[17:44:49] [Worker-Main-13/WARN]: Mixin transformation of team.creative.creativecore.mixin.GroupResourcePackAccessor failed
org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for accessor mixin team.creative.creativecore.mixin.GroupResourcePackAccessor. The mixin is missing from #creativecore:creativecore.mixins.json which owns package team.creative.creativecore.mixin.* and the mixin has not been applied.
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:454) ~[quilt-loader-0.24.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:241) ~[quilt-loader-0.24.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:161) ~[quilt-loader-0.24.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147) ~[quilt-loader-0.24.0-beta.9.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.24.0-beta.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at team.creative.creativecore.common.util.mc.PlatformResourceUtils.length(PlatformResourceUtils.java:15) ~[creativecore-2.11.24.i0:0/:?]
	at team.creative.creativecore.common.util.mc.ResourceUtils.length(ResourceUtils.java:32) ~[creativecore-2.11.24.i0:0/:?]
	at team.creative.creativecore.common.util.mc.ResourceUtils.length(ResourceUtils.java:21) ~[creativecore-2.11.24.i0:0/:?]
	at team.creative.ambientsounds.AmbientSound$SoundStream$1.create(AmbientSound.java:459) ~[ambientsounds-5.3.9.i0:0/:?]
	at net.minecraft.client.sound.RepeatingAudioStream.<init>(RepeatingAudioStream.java:31) ~[minecraft-1.20.1.i0:0/:?]
	at team.creative.ambientsounds.AmbientSound$SoundStream.lambda$getAudioStream$0(AmbientSound.java:450) ~[ambientsounds-5.3.9.i0:0/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by CreativeMD** [comment]
CreativeCore is not compatible with Quilt, sorry but you will have to use fabric instead.

**Comment by Sollace** [comment]
> CreativeCore is not compatible with Quilt, sorry but you will have to use fabric instead.

Ah that's dissapointing. As this is a modpack I will pass the message along. Thank you for taking the time.

**Comment by MimzyFang** [comment]
> CreativeCore is not compatible with Quilt, sorry but you will have to use fabric instead.

Unfortunately it's not possible to move my pack to fabric though since this issue doesn't seem cause any crashes or bigger issues besides some log spam and the creative menu breaking sometimes (which I haven't experienced so far) I will just continue to use it 

Though thanks for the info

**Comment by CreativeMD** [comment]
You can also get around this issue by using the command /cmdclientconfig and changing the setting in ambientsounds -> playSoundWithOffset to false.
