### ISSUE TITLE
[1.12-1.8.5] net.minecraft.worldWorld NoClassDefFoundException

### ISSUE THREAD

**Issue by kreezxil** [CreativeMD/CreativeCore#24]
I've updated my Sky Colony pack to 1.12. The server loads fine but the client crashes with the following error in the console, not the latest.log and with no crash-report file.

```
15:54:47	STDOUT	main	info	[com.creativemd.creativecore.transformer.CreativeTransformer:transform:52]: [creativecore] Patched net.minecraft.world.World ...
15:54:47	LaunchWrapper	main	error	Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
	at net.minecraft.client.main.Main.main(SourceFile:38)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Caused by: java.lang.ClassFormatError: Duplicate field name&signature in class file net/minecraft/world/World
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 9 more```

**Comment by CreativeMD** [comment]
Will be fixed soon.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version.
