### ISSUE TITLE
[1.21neoforge][ConfigHolderObject]NullPointerException about reflect

### ISSUE THREAD

**Issue by ootwclyhe** [CreativeMD/CreativeCore#243]
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1157) ~[?:?] {}
	at java.base/java.lang.reflect.Field.get(Field.java:441) ~[?:?] {}
	at TRANSFORMER/creativecore@2.12.1/team.creative.creativecore.common.config.holder.ConfigHolderObject.<init>(ConfigHolderObject.java:61) ~[CreativeCore_NEOFORGE_v2.12.1_mc1.21.jar%23220!/:2.12.1] {re:classloading}
[crash-2024-07-15_22.14.35-server.txt](https://github.com/user-attachments/files/16235978/crash-2024-07-15_22.14.35-server.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version of CreativeCore. Thanks for reporting this issue!
