### ISSUE TITLE
ModMenu Configuration Bug

### ISSUE THREAD

**Issue by stlouisn** [CreativeMD/CreativeCore#248]
Unable to access configuration for creativecore.

Error:

`[Render thread/ERROR]: Error from mod 'creativecore'
java.lang.NullPointerException: Cannot invoke "team.creative.creativecore.common.config.key.ConfigKey.isFolder()" because "field" is null
	at team.creative.creativecore.common.config.holder.CreativeConfigRegistry.followPath(CreativeConfigRegistry.java:31) ~[CreativeCore_FABRIC_v2.12.4_mc1.21.jar:?]
	at team.creative.creativecore.client.ModMenuImpl.lambda$getConfig$0(ModMenuImpl.java:26) ~[CreativeCore_FABRIC_v2.12.4_mc1.21.jar:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:74) ~[modmenu-11.0.1.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:109) ~[modmenu-11.0.1.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1143) ~[client-intermediary.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:19) ~[modmenu-11.0.1.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.3.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) [lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150) [client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168) [client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:303) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1307) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]`

**Comment by CreativeMD** [comment]
This will be fixed in the newest version of CreativeCore. Also CreativeCore has no configuration anyway.
