### ISSUE TITLE
Mod incompatibility with Moonrise

### ISSUE THREAD

**Issue by clrxbl** [CreativeMD/CreativeCore#255]
The [ShapesMixin](https://github.com/CreativeMD/CreativeCore/blob/375720f6bfcc3e8b9cf5df45fc3a6b5a18dd7823/src/main/java/team/creative/creativecore/mixin/ShapesMixin.java) collides with [Moonrise's](https://github.com/tuinity/moonrise) collision optimizations.

```java
---- Minecraft Crash Report ----
// My bad.

Time: 2024-09-01 15:14:23
Description: Bootstrap

java.lang.ExceptionInInitializerError
	at net.minecraft.class_2966.method_12851(class_2966.java:52)
	at net.minecraft.client.main.Main.main(Main.java:130)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_259 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_2248.method_9541(class_2248.java:154)
	at net.minecraft.class_4770.<clinit>(class_4770.java:28)
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [creativecore.mixins.json:ShapesMixin from mod creativecore] from phase [DEFAULT] in config [creativecore.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_259::joinUnoptimized with priority 1000 cannot inject into net/minecraft/class_259::method_1082(Lnet/minecraft/class_265;Lnet/minecraft/class_265;Lnet/minecraft/class_247;)Lnet/minecraft/class_265; merged by ca.spottedleaf.moonrise.mixin.collisions.ShapesMixin with priority 1000 [INJECT_PREPARE Applicator Phase -> creativecore.mixins.json:ShapesMixin from mod creativecore -> Prepare Injections -> handler$zdp000$creativecore$joinUnoptimized(Lnet/minecraft/class_265;Lnet/minecraft/class_265;Lnet/minecraft/class_247;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare ->  -> { target: method_1082(Lnet/minecraft/class_265;Lnet/minecraft/class_265;Lnet/minecraft/class_247;)Lnet/minecraft/class_265; }]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:312)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:248)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:475)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1407)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more
```

It doesn't look like there's a configuration option to disable this mixin from being applied. In general, seems like a bit of an odd change to be making in a library mod.

**Comment by CreativeMD** [comment]
There are many mods which optimize collison as it is quite broken. For LittleTiles I need some optimizations as well, that's why CreativeCore does that. In theory it is done in a way which should not break other mods as it specifically only does the optimization for stuff related to LittleTiles. Don't see a way to fix it from my end, sorry.
