### ISSUE TITLE
Startup Mixin crash with 2.12.23 on 1.20.1

### ISSUE THREAD

**Issue by brisingraerowing** [CreativeMD/CreativeCore#266]
I'm getting a startup crash on 1.20.1 with 2.12.23.

[Game Output](https://mclo.gs/xa1YN97)

**Comment by DracoHero** [comment]
Me too
[Latest Log](https://github.com/user-attachments/files/17962545/latest.log)

**Comment by deltaminimal** [comment]
Me too!

**Comment by ModernGamingWorld** [comment]
Me as well

**Comment by SafeOfArsenal** [comment]
turkey or chicken?

**Comment by Vinzound** [comment]
Me too!

**Comment by Coraline774477** [comment]
Can confirm that the latest version causes an java.lang.RuntimeException: java.lang.reflect.InvocationTargetException in creativecore.mixins.json:VoxelShapeAccessor->@Accessor[FIELD_SETTER]::setShape(Lnet/minecraft/world/phys/shapes/DiscreteVoxelShape;)V [INJECT Applicator Phase -> creativecore.mixins.json:VoxelShapeAccessor -> Apply Accessors ->  -> Locate -> creativecore.mixins.json:VoxelShapeAccessor->@Accessor[FIELD_SETTER]::setShape(Lnet/minecraft/world/phys/shapes/DiscreteVoxelShape;)V]

For now, everybody (including me) will have to temporarily downgrade to a previously working version of CreativeCore which was 2.12.22 and/or older (preferred downgrade version: 2.12.22) until CreativeMD fixes this major exception. 
Since the game instantaneously crashes at startup when it's the only mod present in the mods folder, no matter if it's client or server.

*Something tells me that whatever he did in 2.12.23 broke something crucial in the mod's coding that possibly needs some refactoring badly to resolve this injection failure.
Since this exception resides in the mod's mixins by the looks of what I'm seeing above (in VoxelShapeAccessor -> DiscreteVoxelShape).

Oh yeah, this possibly is a major issue which 2.12.23 will have to be archived after patching it in 2.12.24.

So expect a patch update (or possibly two or more, depending how serious this InvocationTargetException really is. Since like I said that it's a instant crash from clicking "play" or whatever button it's called when launching the game which indicates that this is a serious exception) coming later on today everyone.

*EDIT: Yeah, this is a injection failure, just as I've said above, which was possibly missed in the dev environment because the injection failure possibly doesn't occur in dev environment. However, outside dev environment this crash will occur because one or more things have possibly been missed when CreativeMD added those new features in 2.12.23; 

[29Nov2024 23:52:54.120] [pool-4-thread-1/FATAL] [mixin/]: Mixin apply failed creativecore.mixins.json:ShapesMixin -> net.minecraft.world.phys.shapes.Shapes: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on joinUnoptimized could not find any targets matching 'joinUnoptimized(Lnet/minecraft/world/phys/shapes/VoxelShape;Lnet/minecraft/world/phys/shapes/VoxelShape;Lnet/minecraft/world/phys/shapes/BooleanOp;)Lnet/minecraft/world/phys/shapes/VoxelShape;' in net.minecraft.world.phys.shapes.Shapes. No refMap loaded. [PREINJECT Applicator Phase -> creativecore.mixins.json:ShapesMixin -> Prepare Injections ->  -> handler$zza000$joinUnoptimized(Lnet/minecraft/world/phys/shapes/VoxelShape;Lnet/minecraft/world/phys/shapes/VoxelShape;Lnet/minecraft/world/phys/shapes/BooleanOp;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on joinUnoptimized could not find any targets matching 'joinUnoptimized(Lnet/minecraft/world/phys/shapes/VoxelShape;Lnet/minecraft/world/phys/shapes/VoxelShape;Lnet/minecraft/world/phys/shapes/BooleanOp;)Lnet/minecraft/world/phys/shapes/VoxelShape;' in net.minecraft.world.phys.shapes.Shapes. No refMap loaded. [PREINJECT Applicator Phase -> creativecore.mixins.json:ShapesMixin -> Prepare Injections ->  -> handler$zza000$joinUnoptimized(Lnet/minecraft/world/phys/shapes/VoxelShape;Lnet/minecraft/world/phys/shapes/VoxelShape;Lnet/minecraft/world/phys/shapes/BooleanOp;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]*
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]

**Comment by ModernGamingWorld** [comment]
@Coraline774477 this is what he changed https://github.com/CreativeMD/CreativeCore/commits/1.20/

**Comment by CreativeMD** [comment]
The issue has been fixed. Something went wrong when compiling the jar. Sorry for the trouble. The newest version should work now. Thanks you all for reporting this issue!

**Comment by Coraline774477** [comment]
> @Coraline774477 this is what he changed https://github.com/CreativeMD/CreativeCore/commits/1.20/

I don't have notifications, so I wasn't notified. Sorry. Also. Thanks CreativeMD for the fix, Now I'll update CreativeCore to 2.12.23. Also it's been that time again for world switch day, which is every sunday or monday of every week. So that my worlds stay interesting and fresh to me. Otherwise I would lose interest into my worlds to keep them alive for longer than a week.
