### ISSUE TITLE
mysterious crash

### ISSUE THREAD

**Issue by due9138** [CreativeMD/CreativeCore#268]
everytime i try opening creativecore for waterframes iget an error message saying 
![image](https://github.com/user-attachments/assets/4b6f163b-c90b-4820-914b-0986818af43d)
ive tried redownloading the mod, trying other versions, and reinstaling neoforge and this error still pops up
how do i fix this?

crashlog:
---- Minecraft Crash Report ----
// Sorry :(

Time: 2024-12-27 21:17:47
Description: Mod loading failures have occurred; consult the issue messages for more details

net.neoforged.neoforge.logging.CrashReportExtender$ModLoadingCrashException: Mod loading has failed

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- Mod loading issue for: creativecore --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/neoforged/neoforge/client/model/geometry/IGeometryLoader
		at TRANSFORMER/creativecore@2.12.27/team.creative.creativecore.CreativeCore.<init>(CreativeCore.java:79) ~[CreativeCore_NEOFORGE_v2.12.27_mc1.21.1.jar%23218!/:2.12.27] {re:mixin,re:classloading}
		at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
		at MC-BOOTSTRAP/fml_loader@6.0.4/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-6.0.4.jar%23120!/:6.0] {}
		at MC-BOOTSTRAP/fml_loader@6.0.4/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-6.0.4.jar%23120!/:6.0] {}
		at MC-BOOTSTRAP/fml_loader@6.0.4/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-6.0.4.jar%23120!/:6.0] {}
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {}
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}
		at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

	Mod file: /C:/Users/User/AppData/Roaming/.minecraft/mods/CreativeCore_NEOFORGE_v2.12.27_mc1.21.1.jar
	Failure message: CreativeCore (creativecore) has failed to load correctly
		java.lang.NoClassDefFoundError: net/neoforged/neoforge/client/model/geometry/IGeometryLoader
	Mod version: 2.12.27
	Mod issues URL: https://github.com/CreativeMD/CreativeCore/issues
	Exception message: java.lang.ClassNotFoundException: net.neoforged.neoforge.client.model.geometry.IGeometryLoader
Stacktrace:
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at TRANSFORMER/creativecore@2.12.27/team.creative.creativecore.CreativeCore.<init>(CreativeCore.java:79) ~[CreativeCore_NEOFORGE_v2.12.27_mc1.21.1.jar%23218!/:2.12.27] {re:mixin,re:classloading}
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@6.0.4/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-6.0.4.jar%23120!/:6.0] {}
	at MC-BOOTSTRAP/fml_loader@6.0.4/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-6.0.4.jar%23120!/:6.0] {}
	at MC-BOOTSTRAP/fml_loader@6.0.4/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-6.0.4.jar%23120!/:6.0] {}
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 288765240 bytes (275 MiB) / 536870912 bytes (512 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 2048.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21921.1000
	Graphics card #1 name: AMD Radeon (TM) 625
	Graphics card #1 vendor: Advanced Micro Devices, Inc.
	Graphics card #1 VRAM (MiB): 2048.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 27.20.11030.11001
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 4096.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 20951.06
	Virtual memory used (MiB): 15402.45
	Swap memory total (MiB): 14870.05
	Swap memory used (MiB): 2700.40
	Space in storage for jna.tmpdir (MiB): available: 55890.69, total: 476304.47
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 55890.69, total: 476304.47
	Space in storage for io.netty.native.workdir (MiB): available: 55890.69, total: 476304.47
	Space in storage for java.io.tmpdir (MiB): available: 55890.69, total: 476304.47
	Space in storage for workdir (MiB): available: 55890.69, total: 476304.47
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 11.0.4+main.d2e20e43
	ModLauncher launch target: neoforgeclient
	ModLauncher services: 
		sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE 
		loader-6.0.4.jar slf4jfixer PLUGINSERVICE 
		loader-6.0.4.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-11.0.1.jar accesstransformer PLUGINSERVICE 
		loader-6.0.4.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		javafml@6.0
		lowcodefml@6.0
		minecraft@6.0
	Mod List: 
		CreativeCore_NEOFORGE_v2.12.27_mc1.21.1.jar       |CreativeCore                  |creativecore                  |2.12.27             |Manifest: NOSIGNATURE
		client-1.21.4-20241203.161809-srg.jar             |Minecraft                     |minecraft                     |1.21.4              |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		neoforge-21.4.46-beta-universal.jar               |NeoForge                      |neoforge                      |21.4.46-beta        |Manifest: NOSIGNATURE
		waterframes-NEOFORGE-mc1.21.1-v2.1.9.jar          |WaterFrames                   |waterframes                   |2.1.9               |Manifest: NOSIGNATURE
		watermedia-2.1.9.jar                              |WaterMedia                    |watermedia                    |2.1.9               |Manifest: NOSIGNATURE
	Crash Report UUID: 9dc51ec6-aa17-4ebf-b865-452f75cf5cec
	FML: 6.0.4
	NeoForge: 21.4.46-beta

**Comment by CreativeMD** [comment]
You cannot use CreativeCore for 1.21.1 for 1.21.4.
