### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by drewtheunreal** [CreativeMD/CreativeCore#43]
i installed creative core for player revive mod and this is the log.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore v1.8.9 mc1.12.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 6/28/19 9:58 AM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
	at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:447)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:139)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:104)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:69)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:343)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:313)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:267)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Linux (amd64) version 4.4.0-148-generic
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 846235416 bytes (807 MB) / 984088576 bytes (938 MB) up to 1304952832 bytes (1244 MB)
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=200M -Xmx1400M -Xms700M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2387 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge.jar) 
	UCHIJAA	forge{14.21.1.2387} [Minecraft Forge] (forge.jar) 
	UCHIJAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAA	codechickenlib{3.1.3.313} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.3.313-universal.jar) 
	UCHIJAA	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.8.9 mc1.12.jar) 
	UCHIJAA	jei{4.7.5.86} [Just Enough Items] (jei_1.12-4.7.5.86.jar) 
	UCHIJAA	playerrevive{1.0} [Player Revive] (PlayerRevive v1.2.3 mc1.12.jar) 
	UCHIJAA	veinminer{0.38.2} [Vein Miner] (VeinMiner-1.12-0.38.2.647+b31535a.jar) 
	UCHIJAA	veinminermodsupport{0.38.2} [Mod Support] (VeinMiner-1.12-0.38.2.647+b31535a.jar) 
	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore v1.8.9 mc1.12.jar)
  
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by CreativeMD** [comment]
You should update to 1.12.2 and update all of my mods.

**Comment by drewtheunreal** [comment]
ok. thanks.
