### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Muxasii** [CreativeMD/CreativeCore#52]
**Error: java.lang.NoClassDefFoundError: com/creativemd/creativecore/gui/opener/CustomGuiHandler**

I've tried most of the versions of CreativeCore, and none of them seem to work. 

> java.lang.NoClassDefFoundError: com/creativemd/creativecore/gui/opener/CustomGuiHandler
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
> 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
> 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.gui.opener.CustomGuiHandler
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 38 more
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
> 	... 40 more

Forge version is 14.23.5.2781

**Comment by Muxasii** [comment]
I removed all mods but it and the one that depends on it and it still crashed. I then removed the one that depends on it and it worked. Must have something to do with LittleTiles. I'll mess with different versions of LittleTiles to see if it has to do with the version I have.
