### ISSUE TITLE
crash when i start the game

### ISSUE THREAD

**Issue by Monkey421** [CreativeMD/CreativeCore#61]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.5_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre180_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 3/19/20 3:00 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/creativemd/creativecore/core/CreativeCoreClient
	at com.creativemd.littletiles.client.LittleTilesClient.loadSide(LittleTilesClient.java:277)
	at com.creativemd.littletiles.LittleTiles.registerItems(LittleTiles.java:262)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_LittleTiles_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.core.CreativeCoreClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.client.LittleTilesClient.loadSide(LittleTilesClient.java:277)
	at com.creativemd.littletiles.LittleTiles.registerItems(LittleTiles.java:262)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_LittleTiles_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 331916664 bytes (316 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version                      | Source                                                         | Signature |
	|:----- |:----------------- |:---------------------------- |:-------------------------------------------------------------- |:--------- |
	| LCH   | minecraft         | 1.12.2                       | minecraft.jar                                                  | None      |
	| LCH   | mcp               | 9.42                         | minecraft.jar                                                  | None      |
	| LCH   | FML               | 8.0.99.99                    | forge-1.12.2-14.23.5.2847.jar                                  | None      |
	| LCH   | forge             | 14.23.5.2847                 | forge-1.12.2-14.23.5.2847.jar                                  | None      |
	| LCH   | creativecoredummy | 1.0.0                        | minecraft.jar                                                  | None      |
	| LCH   | littletilescore   | 1.0.0                        | minecraft.jar                                                  | None      |
	| LCH   | obfuscate         | 0.2.6                        | minecraft.jar                                                  | None      |
	| LCH   | securitycraft     | v1.8.17                      | [1.12.2]+SecurityCraft+v1.8.17.jar                             | None      |
	| LCH   | cdm               | 0.4.1                        | cdm-0.4.1-mc1.12.2.jar                                         | None      |
	| LCH   | cgm               | 0.15.3                       | cgm-0.15.3-mc1.12.2.jar                                        | None      |
	| LCH   | chiselsandbits    | 14.33                        | chiselsandbits-14.33.jar                                       | None      |
	| LCH   | creativecore      | 1.10.0                       | CreativeCore_v1.10.5_mc1.12.2.jar                              | None      |
	| LCH   | cfm               | 6.3.1                        | furniture-6.3.1-1.12.2.jar                                     | None      |
	| LCH   | littletiles       | 1.5.0                        | LittleTiles_v1.5.0-pre180_mc1.12.2.jar                         | None      |
	| LCH   | vehicle           | 0.41.0                       | vehicle-mod-0.41.0-1.12.2.jar                                  | None      |
	| LCH   | worldedit         | 6.1.10-SNAPSHOT              | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar              | None      |
	| LCH   | worldeditcuife2   | 2.2.0-mf-1.12.2-14.23.5.2768 | WorldEdit+CUI+Forge+Edition+2-2.2.0-mf-1.12.2-14.23.5.2768.jar | None      |

	Loaded coremods (and transformers): 
LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  com.creativemd.littletiles.LittleTilesLateTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CreativePatchingLoader (CreativeCore_v1.10.5_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre180_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.59' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.59, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by Monkey421** [comment]
nvm i just reverted to the older version
