### ISSUE TITLE
Crash with CreativeCore 1.12

### ISSUE THREAD

**Issue by C0deC** [CreativeMD/CreativeCore#62]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  iceandfire (iceandfire-1.8.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  CreativePatchingLoader (CreativeCore_v1.10.3_mc1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.21.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 3/21/20 4:26 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CreativeCore (creativecore)
Caused by: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at com.creativemd.creativecore.common.config.event.ConfigEventHandler.load(ConfigEventHandler.java:214)
	at com.creativemd.creativecore.common.config.holder.CreativeConfigRegistry.load(CreativeConfigRegistry.java:44)
	at com.creativemd.creativecore.CreativeCore.PreInit(CreativeCore.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 420238888 bytes (400 MB) / 939524096 bytes (896 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F4 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version           | Source                                        | Signature                                |
	|:----- |:----------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCH   | mcp               | 9.42              | minecraft.jar                                 | None                                     |
	| LCH   | FML               | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCH   | forge             | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCH   | creativecoredummy | 1.0.0             | minecraft.jar                                 | None                                     |
	| LCH   | securitycraft     | v1.8.15           | [1.12.2]+SecurityCraft+v1.8.15.jar            | None                                     |
	| LCH   | baubles           | 1.5.2             | Baubles-1.12-1.5.2 (5).jar                    | None                                     |
	| LCH   | astralsorcery     | 1.10.21           | astralsorcery-1.12.2-1.10.21.jar              | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCH   | bettercaves       | 1.12.2            | bettercaves-1.12.2-1.6.0.jar                  | None                                     |
	| LCH   | byg               | 1.7.1             | BiomesYouGo1.7.1.jar                          | None                                     |
	| LCH   | bloodmoon         | 1.5.3             | Bloodmoon-MC1.12.2-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | bookworm          | 1.12.2-2.3.0      | bookworm-1.12.2-2.3.0.jar                     | None                                     |
	| LCH   | ctm               | MC1.12.2-1.0.1.30 | CTM-MC1.12.2-1.0.1.30.jar                     | None                                     |
	| LCH   | jei               | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCH   | chisel            | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44.jar                  | None                                     |
	| LCH   | configmod         | v1.0              | coroutil-1.12.1-1.2.36.jar                    | None                                     |
	| LCH   | extendedrenderer  | v1.0              | coroutil-1.12.1-1.2.36.jar                    | None                                     |
	| LCH   | coroutil          | 1.12.1-1.2.36     | coroutil-1.12.1-1.2.36.jar                    | None                                     |
	| LCH   | playerrevive      | 1.0               | PlayerRevive_v1.2.31_mc1.12.2.jar             | None                                     |
	| LCE   | creativecore      | 1.10.0            | CreativeCore_v1.10.3_mc1.12.2.jar             | None                                     |
	| LC    | customspawner     | 3.11.4            | CustomMobSpawner-3.11.4.jar                   | None                                     |
	| LC    | ptrmodellib       | 1.0.4             | PTRLib-1.0.4 (2).jar                          | None                                     |
	| LC    | props             | 2.6.3             | Decocraft-2.6.3_1.12.2 (2).jar                | None                                     |
	| LC    | mocreatures       | 12.0.5            | DrZharks MoCreatures Mod-12.0.5.jar           | None                                     |
	| LC    | dynamictrees      | 1.12.2-0.9.6      | DynamicTrees-1.12.2-0.9.6 (3).jar             | None                                     |
	| LC    | elevatorid        | 1.3.12            | ElevatorMod-1.12.2-1.3.12.jar                 | None                                     |
	| LC    | extrautils2       | 1.0               | extrautils2-1.12-1.9.9 (2).jar                | None                                     |
	| LC    | ferdinandsflowers | 1.10.4.1          | Ferdinand's+Flowers-1.12.x-1.10.4.1 (2).jar   | None                                     |
	| LC    | gokistats         | @version@         | Goki-Stats-Mod-1.12.2.jar                     | None                                     |
	| LC    | waila             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LC    | llibrary          | 1.7.19            | llibrary-1.7.19-1.12.2 (4).jar                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | iceandfire        | 1.8.4             | iceandfire-1.8.4.jar                          | None                                     |
	| LC    | journeymap        | 1.12.2-5.5.6      | journeymap-1.12.2-5.5.6.jar                   | None                                     |
	| LC    | leatherworks      | 1.78.0            | LeatherWorks-1.12-1.78.0.42.jar               | None                                     |
	| LC    | mca               | 6.1.0             | MCA-1.12.2-6.1.0-universal.jar                | None                                     |
	| LC    | playerskins       | 1.0.4             | playerskin-1.12.2-1.0.5.jar                   | None                                     |
	| LC    | railcraft         | 12.0.0            | railcraft-12.0.0 (1).jar                      | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | reap              | 1.5.2             | reap-1.5.2.jar                                | None                                     |
	| LC    | tombstone         | 3.6.5             | tombstone-3.6.5-1.12.2.jar                    | None                                     |
	| LC    | traverse          | 1.6.0             | Traverse-1.12.2-1.6.0-69 (1).jar              | None                                     |
	| LC    | twilightforest    | 3.10.1013         | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
	| LC    | weather2          | 1.12.1-2.6.12     | weather2-1.12.1-2.6.12 (3).jar                | None                                     |
	| LC    | zawa              | 1.12.2-1.7.0      | zawa-1.12.2-1.7.0.jar                         | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
iceandfire (iceandfire-1.8.4.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CreativePatchingLoader (CreativeCore_v1.10.3_mc1.12.2.jar)
  
AstralCore (astralsorcery-1.12.2-1.10.21.jar)
  
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.74' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-Renewed-Shaders-All-Versions-Standard (2).zip
	OpenGlVersion: 4.6.0 NVIDIA 442.74
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by CreativeMD** [comment]
This looks like a corrupted config file. You might want to delete the config files of CreativeCore and PlayerRevive, Furthermore update CreativeCore. If the issue still persists open a new issue.
