### ISSUE TITLE
CRASH 1.12.2

### ISSUE THREAD

**Issue by raulfpv** [CreativeMD/CreativeCore#65]
Hello friends, I have this bug. Can you help me? thanks
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.68_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 3/28/20 2:50 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Player is not online!
	at com.feed_the_beast.ftblib.lib.data.ForgePlayer.getPlayer(ForgePlayer.java:266)
	at com.feed_the_beast.ftblib.lib.data.ForgePlayer.getContext(ForgePlayer.java:490)
	at com.feed_the_beast.ftblib.lib.data.ForgePlayer.getRankConfig(ForgePlayer.java:503)
	at com.feed_the_beast.ftbutilities.data.FTBUtilitiesTeamData.getMaxClaimChunks(FTBUtilitiesTeamData.java:274)
	at com.feed_the_beast.ftbutilities.net.MessageClaimedChunksUpdate.<init>(MessageClaimedChunksUpdate.java:62)
	at com.feed_the_beast.ftbutilities.data.ClaimedChunks.update(ClaimedChunks.java:151)
	at com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesServerEventHandler.onServerTick(FTBUtilitiesServerEventHandler.java:176)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_63_FTBUtilitiesServerEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 863397720 bytes (823 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                        | Signature |
	|:------ |:----------------- |:------------ |:--------------------------------------------- |:--------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                                 | None      |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                                 | None      |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar                 | None      |
	| LCHIJA | forge             | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar                 | None      |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                                 | None      |
	| LCHIJA | creativecore      | 1.9.9        | CreativeCore_v1.9.68_mc1.12.2.jar             | None      |
	| LCHIJA | ftblib            | 5.4.3.141    | FTBLib-5.4.3.141.jar                          | None      |
	| LCHIJA | ftbutilities      | 5.4.0.107    | FTBUtilities-5.4.0.107.jar                    | None      |
	| LCHIJA | gottschcore       | 1.8.0        | GottschCore-mc1.12.2-f14.23.5.2768-v1.8.0.jar | None      |
	| LCHIJA | journeymap        | 1.12.2-5.5.5 | journeymap-1.12.2-5.5.5.jar                   | None      |
	| LCHIJA | moderncreater     | 1.4.0        | modern-creator-1.4.0.jar                      | None      |
	| LCHIJA | realsurvivor      | 1.0.5        | real-survivor-1.1.5.jar                       | None      |
	| LCHIJA | treasure2         | 1.5.1        | Treasure2-mc1.12.2-f14.23.5.2768-v1.5.1.jar   | None      |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.68_mc1.12.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Player'/305, l='New World', x=-54.24, y=71.00, z=-90.09]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 425.31
	OpenGlRenderer: GeForce GTX 660M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by CreativeMD** [comment]
This issue is not related to any of my mods (btw CreativeCore is way outdated).
