### ISSUE TITLE
Prevents my launcher from opening

### ISSUE THREAD

**Issue by NatGod** [CreativeMD/CreativeCore#66]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.10.3_mc1.12.2 (COMPLEMENTO OnlinePicFrame).jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3 (AUMENTO DIFICULTAD TEMPORAL).jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 3/23/20 4:50 PM
XRay version: 58
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CreativeCore (creativecore)
Caused by: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at com.creativemd.creativecore.common.config.event.ConfigEventHandler.load(ConfigEventHandler.java:214)
	at com.creativemd.creativecore.common.config.holder.CreativeConfigRegistry.load(CreativeConfigRegistry.java:44)
	at com.creativemd.creativecore.CreativeCore.PreInit(CreativeCore.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 103057728 bytes (98 MB) / 340230144 bytes (324 MB) up to 2725511168 bytes (2599 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx2612M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F4 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version        | Source                                                                | Signature                                |
	|:----- |:-------------------------- |:-------------- |:--------------------------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                  | 1.12.2         | minecraft.jar                                                         | None                                     |
	| LCH   | mcp                        | 9.42           | minecraft.jar                                                         | None                                     |
	| LCH   | FML                        | 8.0.99.99      | forge-1.12.2-14.23.5.2847.jar                                         | None                                     |
	| LCH   | forge                      | 14.23.5.2847   | forge-1.12.2-14.23.5.2847.jar                                         | None                                     |
	| LCH   | creativecoredummy          | 1.0.0          | minecraft.jar                                                         | None                                     |
	| LCH   | securitycraft              | v1.8.17        | [1.12.2]+SecurityCraft+v1.8.17 (SEGURIDAD DE BLOQUES).jar             | None                                     |
	| LCH   | bloodmoon                  | 1.5.3          | Bloodmoon-MC1.12.2-1.5.3 (AUMENTO DIFICULTAD TEMPORAL).jar            | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | opframe                    | 1.4.0          | OnlinePicFrame_v1.4.35_mc1.12.2 (CUADROS PRESONALIZADOS).jar          | None                                     |
	| LCE   | creativecore               | 1.10.0         | CreativeCore_v1.10.3_mc1.12.2 (COMPLEMENTO OnlinePicFrame).jar        | None                                     |
	| LC    | ptrmodellib                | 1.0.4          | PTRLib-1.0.4 (COMPLEMENTO Decocraft).jar                              | None                                     |
	| LC    | props                      | 2.6.3          | Decocraft-2.6.3_1.12.2 (INTERIORES DECORACION).jar                    | None                                     |
	| LC    | dynamictrees               | 1.12.2-0.9.7   | DynamicTrees-1.12.2-0.9.7 (ARBOLES CAIDOS).jar                        | None                                     |
	| LC    | ferdinandsflowers          | 1.10.4.1       | Ferdinand's+Flowers-1.12.x-1.10.4.1 (FLORES Y BLOQUES DE COLORES).jar | None                                     |
	| LC    | ichunutil                  | 7.2.2          | iChunUtil-1.12.2-7.2.2 (COMPLEMENTO MobDismemberment).jar             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | mcjtylib_ng                | 3.5.4          | mcjtylib-1.12-3.5.4 (COMPLEMENTO immcraft).jar                        | None                                     |
	| LC    | immcraft                   | 1.6.0          | immcraft-1.12-1.6.0 (OBJEYTOS EN EL SUELO).jar                        | None                                     |
	| LC    | jei                        | 4.15.0.291     | jei_1.12.2-4.15.0.291 (INVENTARIO EXTENSO).jar                        | None                                     |
	| LC    | leatherworks               | 1.78.0         | LeatherWorks-1.12-1.78.0.42 (MOCHILAS Y MAS).jar                      | None                                     |
	| LC    | mca                        | 6.1.0          | MCA-1.12.2-6.1.0-universal (ALDEANOS).jar                             | None                                     |
	| LC    | mobdismemberment           | 7.0.0          | MobDismemberment-1.12.2-7.0.0 (DESMENBRAMIENTO).jar                   | None                                     |
	| LC    | morpheus                   | 1.12.2-3.5.106 | Morpheus-1.12.2-3.5.106 (SUEÑO SUBITO).jar                            | None                                     |
	| LC    | tlauncher_custom_cape_skin | 1.4            | tlskincape_1.12.2-1.4.jar                                             | None                                     |
	| LC    | tombstone                  | 3.6.9          | tombstone-3.6.9-1.12.2 (RIP MODE).jar                                 | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.10.3_mc1.12.2 (COMPLEMENTO OnlinePicFrame).jar)
  
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3 (AUMENTO DIFICULTAD TEMPORAL).jar)
  lumien.bloodmoon.asm.ClassTransformer
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 25.20.100.6518' Renderer: 'Intel(R) HD Graphics 620'
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 25.20.100.6518
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by CreativeMD** [comment]
Please update CreativeCore and remove the mod config file of OnlinePictureFrame and CreativeCore.
