### ISSUE TITLE
Crash on 1.12 with forge 14.23.5.2847 and v1.10.9 version of CreativeCore

### ISSUE THREAD

**Issue by DarthSidious666** [CreativeMD/CreativeCore#69]
Here's my crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  weaponlib (mw_2.0-0.4.1_mc1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.74-core.jar)
  SoundUnpack (OpenSecurity-1.12.2-1.0-39.jar)
  LittlePatchingLoader (LittleTiles+v1.5.0-pre31+mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  CreativePatchingLoader (CreativeCore_v1.10.9_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 4/2/20 1:50 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/creativemd/creativecore/gui/opener/CustomGuiHandler
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.gui.opener.CustomGuiHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1118863088 bytes (1067 MB) / 2147483648 bytes (2048 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version           | Source                                          | Signature                                |
	|:----- |:--------------------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                         | 1.12.2            | minecraft.jar                                   | None                                     |
	| LC    | mcp                               | 9.42              | minecraft.jar                                   | None                                     |
	| LC    | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LC    | forge                             | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LC    | creativecoredummy                 | 1.0.0             | minecraft.jar                                   | None                                     |
	| LC    | littletilescore                   | 1.0.0             | minecraft.jar                                   | None                                     |
	| LC    | opencomputers|core                | 1.7.5.192         | minecraft.jar                                   | None                                     |
	| LC    | redstoneflux                      | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                          | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar          | None                                     |
	| LC    | opencomputers                     | 1.7.5.192         | OpenComputers-MC1.12.2-1.7.5.192.jar            | None                                     |
	| LC    | aunis                             | 1.8.3-beta        | aunis-1.12.2-1.8.3-beta.jar                     | None                                     |
	| LC    | ctm                               | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                       | None                                     |
	| LC    | jei                               | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                       | None                                     |
	| LC    | chisel                            | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                    | None                                     |
	| LC    | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | cofhworld                         | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | creativecore                      | 1.10.0            | CreativeCore_v1.10.9_mc1.12.2.jar               | None                                     |
	| LC    | endercore                         | 1.12.2-0.5.74     | EnderCore-1.12.2-0.5.74.jar                     | None                                     |
	| LC    | thermalfoundation                 | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion                  | 5.5.4             | ThermalExpansion-1.12.2-5.5.4.43-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | enderio                           | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LC    | enderiointegrationtic             | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LC    | enderiobase                       | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LC    | enderioconduits                   | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LC    | enderioconduitsrefinedstorage     | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LC    | enderiointegrationforestry        | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LC    | enderiointegrationticlate         | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LC    | enderiomachines                   | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LC    | enderiopowertools                 | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                       | None                                     |
	| LC    | cfm                               | 6.3.1             | furniture-6.3.1-1.12.2.jar                      | None                                     |
	| LC    | journeymap                        | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                     | None                                     |
	| L     | littletiles                       | 1.5.0             | LittleTiles+v1.5.0-pre31+mc1.12.2.jar           | None                                     |
	| L     | mcjtylib_ng                       | 3.5.4             | mcjtylib-1.12-3.5.4.jar                         | None                                     |
	| L     | mw                                | 0.4.1             | mw_2.0-0.4.1_mc1.12.2.jar                       | None                                     |
	| L     | opensecurity                      | 1.0-39            | OpenSecurity-1.12.2-1.0-39.jar                  | None                                     |

	Loaded coremods (and transformers): 
weaponlib (mw_2.0-0.4.1_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.74-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
SoundUnpack (OpenSecurity-1.12.2-1.0-39.jar)
  
LittlePatchingLoader (LittleTiles+v1.5.0-pre31+mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CreativePatchingLoader (CreativeCore_v1.10.9_mc1.12.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.50' Renderer: 'GeForce GTX 1070 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.50, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz

Downloading 1.9.0-pre1 works though.
I've tried downloading 1.10.9 a few times thinking it was a corrupted file but minecraft fails to load each time with this version.

**Comment by CreativeMD** [comment]
Your LittleTiles version is way outdated, just update it and everything should work fine.
