### ISSUE TITLE
Creative Core crashes game

### ISSUE THREAD

**Issue by logangamesdaily** [CreativeMD/CreativeCore#78]
REPORT HERE :
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore-1.12.2.jar)
  LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 6/4/20 8:04 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/creativemd/creativecore/core/CreativeCoreClient
	at com.creativemd.littletiles.client.LittleTilesClient.loadSide(LittleTilesClient.java:252)
	at com.creativemd.littletiles.LittleTiles.registerItems(LittleTiles.java:265)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_LittleTiles_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.core.CreativeCoreClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.client.LittleTilesClient.loadSide(LittleTilesClient.java:252)
	at com.creativemd.littletiles.LittleTiles.registerItems(LittleTiles.java:265)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_LittleTiles_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 731178696 bytes (697 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version      | Source                          | Signature                                |
	|:----- |:----------------- |:------------ |:------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2       | minecraft.jar                   | None                                     |
	| LCH   | mcp               | 9.42         | minecraft.jar                   | None                                     |
	| LCH   | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy | 1.0.0        | minecraft.jar                   | None                                     |
	| LCH   | littletilescore   | 1.0.0        | minecraft.jar                   | None                                     |
	| LCH   | cdm               | 0.4.1        | cdm-0.4.1-mc1.12.2.jar          | None                                     |
	| LCH   | cfm               | 6.3.0        | cfm-6.3.0-mc1.12.2.jar          | None                                     |
	| LCH   | creativecore      | 1.10.0       | CreativeCore-1.12.2.jar         | None                                     |
	| LCH   | customnpcs        | 1.12         | CustomNPCs_1.12.2-(01Oct19).jar | None                                     |
	| LCH   | jei               | 4.15.0.293   | jei_1.12.2-4.15.0.293.jar       | None                                     |
	| LCH   | littletiles       | 1.5.0        | LittleTiles-Mod-1.12.2.jar      | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore-1.12.2.jar)
  
LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7263' Renderer: 'Intel(R) UHD Graphics 600'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 600 GL version 4.6.0 - Build 26.20.100.7263, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Celeron(R) N4000 CPU @ 1.10GHz

**Comment by logangamesdaily** [comment]
Help!

**Comment by CreativeMD** [comment]
Please download CreativeCore and LittleTiles from curseforge and not any other website.
