### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by LemADEC** [CreativeMD/CreativeCore#8]
With 1.3.13 on dedicated server mode, game crashes trying to load client side code:
```
[20:47:27 ERROR]: Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
[20:47:27 ERROR]:
>       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>       UCHI    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
>       UCHI    FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1481.148-server.jar)
>       UCHI    Forge{10.13.4.1481} [Minecraft Forge] (KCauldron-1.7.10-1481.148-server.jar)
>       UCHI    kimagine{0.1} [KImagine] (minecraft.jar)
>       UCHI    CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar)
>       UCHI    itemphysic{1.1.5} [ItemPhysic] (minecraft.jar)
>       UCHI    NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar)
>       UCHE    creativecore{1.2.0} [CreativeCore] (CreativeCore v1.3.13 mc1.7.10.jar)
[20:47:27 ERROR]: The following problems were captured during this phase
[20:47:27 ERROR]: Caught exception from creativecore
java.lang.NoClassDefFoundError: net/minecraft/client/gui/inventory/GuiContainer
>       at com.creativemd.creativecore.core.CreativeCore.Init(CreativeCore.java:72) ~[CreativeCore.class:?]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_85]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_85]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_85]
>       at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_85]
>       at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:1.7.10-1481.148]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_85]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_85]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_85]
>       at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_85]
>       at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
>       at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-1481.148]
>       at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-1481.148]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_85]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_85]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_85]
>       at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_85]
>       at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
>       at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-1481.148]
>       at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737) [Loader.class:1.7.10-1481.148]
>       at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:1.7.10-1481.148]
>       at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324) [FMLCommonHandler.class:1.7.10-1481.148]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:287) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.inventory.GuiContainer
>       at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_85]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_85]
>       ... 33 more
Caused by: java.lang.RuntimeException: Attempted to load class bex for invalid side SERVER
>       at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51) ~[KCauldron-1.7.10-1481.148-server.jar:1.7.10-1481.148]
>       at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
>       at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_85]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_85]
>       ... 33 more
[20:47:27 ERROR]: Encountered an unexpected exception
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/gui/inventory/GuiContainer
>
>       at cpw.mods.fml.common.LoadController.transition(LoadController.java:163) ~[LoadController.class:1.7.10-1481.148]
>       at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739) ~[Loader.class:1.7.10-1481.148]
>       at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:1.7.10-1481.148]
>       at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324) ~[FMLCommonHandler.class:1.7.10-1481.148]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:287) ~[lt.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/inventory/GuiContainer
>       at com.creativemd.creativecore.core.CreativeCore.Init(CreativeCore.java:72) ~[CreativeCore.class:?]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_85]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_85]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_85]
>       at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_85]
>       at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:1.7.10-1481.148]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_85]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_85]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_85]
>       at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_85]
>       at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
>       at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-1481.148]
>       at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-1481.148]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_85]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_85]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_85]
>       at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_85]
>       at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
>       at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
>       at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:1.7.10-1481.148]
>       at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737) ~[Loader.class:1.7.10-1481.148]
>       ... 5 more
```

**Comment by CreativeMD** [comment]
It will be fixed in the next version

**Comment by CreativeMD** [comment]
Should be fixed now
