### ISSUE TITLE
1.12.2 creative core v1.10.16 crash

### ISSUE THREAD

**Issue by Jennifercutixx** [CreativeMD/CreativeCore#83]
load up the game and then crashes with 
![Untitled](https://user-images.githubusercontent.com/60190810/87834441-57a5aa80-c882-11ea-9320-77fde44f22cd.png)
crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.27_mc1.12.2.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7/17/20 10:50 PM
Description: Initializing game

java.lang.NoSuchMethodError: com.creativemd.creativecore.common.packet.CreativeCorePacket.registerPacket(Ljava/lang/Class;Ljava/lang/String;)V
	at com.creativemd.itemphysic.ItemDummyContainer.initFull(ItemDummyContainer.java:79)
	at com.creativemd.itemphysic.ItemDummyContainer.init(ItemDummyContainer.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.itemphysic.ItemDummyContainer.initFull(ItemDummyContainer.java:79)
	at com.creativemd.itemphysic.ItemDummyContainer.init(ItemDummyContainer.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1039305456 bytes (991 MB) / 4563402752 bytes (4352 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 135 mods loaded, 135 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version               | Source                                           | Signature                                |
	|:----- |:-------------------------------------------- |:--------------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHI  | minecraft                                    | 1.12.2                | minecraft.jar                                    | None                                     |
	| LCHI  | mcp                                          | 9.42                  | minecraft.jar                                    | None                                     |
	| LCHI  | FML                                          | 8.0.99.99             | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                                        | 14.23.5.2854          | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | creativecoredummy                            | 1.0.0                 | minecraft.jar                                    | None                                     |
	| LCH   | itemphysic                                   | 1.4.0                 | minecraft.jar                                    | None                                     |
	| LCH   | micdoodlecore                                |                       | minecraft.jar                                    | None                                     |
	| LCH   | com.elytradev.movingworld.common.asm.coremod |                       | minecraft.jar                                    | None                                     |
	| LCH   | openmodscore                                 | 0.12.2                | minecraft.jar                                    | None                                     |
	| LCH   | foamfixcore                                  | 7.7.4                 | minecraft.jar                                    | None                                     |
	| LCH   | movillages                                   | 1.5.4                 | [1.12]MoVillages-1.5.4.jar                       | None                                     |
	| LCH   | antiqueatlas                                 | 4.6.3                 | antiqueatlas-1.12.2-4.6.3.jar                    | None                                     |
	| LCH   | antiqueatlasoverlay                          | 1.2                   | antiqueatlas-1.12.2-4.6.3.jar                    | None                                     |
	| LCH   | jei                                          | 4.15.0.289            | jei_1.12.2-4.15.0.289.jar                        | None                                     |
	| LCH   | appleskin                                    | 1.0.9                 | AppleSkin-mc1.12-1.0.9.jar                       | None                                     |
	| LCH   | ebwizardry                                   | 4.2.8                 | ElectroblobsWizardry-4.2.8-MC1.12.2.jar          | None                                     |
	| LCH   | arcane_essentials                            | 1.0                   | Arcane+Essentials-0.9.2.jar                      | None                                     |
	| LCH   | carrots                                      | 1.0.0b1               | carrotslib-mc1.12.2-1.0.0b1.jar                  | None                                     |
	| LCH   | armorunder                                   | 1.0.0                 | armorunder-mc1.12.2-1.0.0.jar                    | None                                     |
	| LCH   | waystones                                    | 4.1.0                 | Waystones_1.12.2-4.1.0.jar                       | None                                     |
	| LCH   | atlasextras                                  | 1.7                   | AtlasExtras-1.12.2-1.7.jar                       | None                                     |
	| LCH   | quark                                        | r1.6-179              | Quark-r1.6-179.jar                               | None                                     |
	| LCH   | autoreglib                                   | 1.3-32                | AutoRegLib-1.3-32.jar                            | None                                     |
	| LCH   | bno                                          | 1.12.2-1.0.4.0        | BasicNetherOres-1.12.2-1.0.4.0.jar               | None                                     |
	| LCH   | baubles                                      | 1.5.2                 | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCH   | baubleshud                                   | 5.0.2                 | BaublesHud-1.12.2-5.0.2.jar                      | None                                     |
	| LCH   | bettercombatmod                              | 1.5.6                 | BetterCombat-1.12.2-1.5.6.jar                    | None                                     |
	| LCH   | blur                                         | 1.0.4-14              | Blur-1.0.4-14.jar                                | None                                     |
	| LCH   | bountifulbaubles                             | 0.0.1                 | Bountiful+Baubles-1.12.2-0.1.5.jar               | None                                     |
	| LCH   | buildcraftlib                                | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                     | None                                     |
	| LCH   | buildcraftcore                               | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                     | None                                     |
	| LCH   | buildcraftbuilders                           | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                     | None                                     |
	| LCH   | buildcrafttransport                          | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                     | None                                     |
	| LCH   | buildcraftsilicon                            | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                     | None                                     |
	| LCH   | crafttweaker                                 | 4.1.20                | CraftTweaker2-1.12-4.1.20.564.jar                | None                                     |
	| LCH   | buildcraftcompat                             | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                     | None                                     |
	| LCH   | buildcraftenergy                             | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                     | None                                     |
	| LCH   | buildcraftfactory                            | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                     | None                                     |
	| LCH   | buildcraftrobotics                           | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                     | None                                     |
	| LCH   | cave_expansion                               | 1.5.0                 | CaveExpansionV1.5.jar                            | None                                     |
	| LCH   | cavegenerator                                | 0.14                  | CaveGenerator-0.14.jar                           | None                                     |
	| LCH   | cat                                          | 0.1                   | CavesAndDungeonsMod.jar                          | None                                     |
	| LCH   | chesttransporter                             | 2.8.8                 | ChestTransporter-1.12.2-2.8.8.jar                | None                                     |
	| LCH   | ctm                                          | MC1.12.2-0.3.3.22     | CTM-MC1.12.2-0.3.3.22.jar                        | None                                     |
	| LCH   | chisel                                       | MC1.12.2-0.2.1.35     | Chisel-MC1.12.2-0.2.1.35.jar                     | None                                     |
	| LCH   | chunkanimator                                | 1.2                   | ChunkAnimator-MC1.12-1.2.jar                     | None                                     |
	| LCH   | clumps                                       | 3.1.2                 | Clumps-3.1.2.jar                                 | None                                     |
	| LCH   | codechickenlib                               | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | toughasnails                                 | 3.1.0.141             | ToughAsNails-1.12.2-3.1.0.141-universal.jar      | None                                     |
	| LCH   | comforts                                     | 1.4.1.2               | comforts-1.12.2-1.4.1.2.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCH   | controlling                                  | 3.0.7                 | Controlling-3.0.7.jar                            | None                                     |
	| LCH   | cookingforblockheads                         | 6.5.0                 | CookingForBlockheads_1.12.2-6.5.0.jar            | None                                     |
	| LCH   | coralreef                                    | 2.0                   | CoralReef-2.5-1.12.2.jar                         | None                                     |
	| LCH   | cosmiclib                                    | 0.4.0                 | CosmicLib-1.12.2-0.4.0.BETA.jar                  | d3974446c00f9f1d275edce305771eeddf30c658 |
	| LCH   | ctgui                                        | 1.0.0                 | CraftTweaker2-1.12-4.1.20.564.jar                | None                                     |
	| LCH   | crafttweakerjei                              | 2.0.3                 | CraftTweaker2-1.12-4.1.20.564.jar                | None                                     |
	| LCH   | enhancedvisuals                              | 1.3.0                 | EnhancedVisuals_v1.3.15_mc1.12.2.jar             | None                                     |
	| LCH   | creativecore                                 | 1.10.0                | CreativeCore_v1.10.16_mc1.12.2.jar               | None                                     |
	| LCH   | customspawner                                | 3.11.4                | CustomMobSpawner-3.11.5.jar                      | None                                     |
	| LCH   | cxlibrary                                    | 1.6.1                 | cxlibrary-1.12.1-1.6.1.jar                       | None                                     |
	| LCH   | death_compass                                | 0.0.3                 | DeathCompass-0.0.3.jar                           | None                                     |
	| LCH   | ptrmodellib                                  | 1.0.4                 | PTRLib-1.0.4.jar                                 | None                                     |
	| LCH   | props                                        | 2.6.3                 | Decocraft-2.6.3_1.12.2.jar                       | None                                     |
	| LCH   | disenchanter                                 | 1.6                   | disenchanter-[1.12]1.6.jar                       | None                                     |
	| LCH   | mocreatures                                  | 12.0.5                | DrZharks MoCreatures Mod-12.0.5.jar              | None                                     |
	| LCH   | galacticraftcore                             | 4.0.2.244             | GalacticraftCore-1.12.2-4.0.2.244.jar            | None                                     |
	| LCH   | sereneseasons                                | 1.2.18                | SereneSeasons-1.12.2-1.2.18-universal.jar        | None                                     |
	| LCH   | orelib                                       | 3.6.0.1               | OreLib-1.12.2-3.6.0.1.jar                        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround                                    | 3.6.0.2               | DynamicSurroundings-1.12.2-3.6.0.2.jar           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dynamictrees                                 | 1.12.2-0.9.6          | DynamicTrees-1.12.2-0.9.6.jar                    | None                                     |
	| LCH   | harvestcraft                                 | 1.12.2zb              | Pam's+HarvestCraft+1.12.2zf.jar                  | None                                     |
	| LCH   | dynamictreesphc                              | 1.12.2-1.4.2          | DynamicTreesPHC-1.12.2-1.4.2.jar                 | None                                     |
	| LCH   | fairylights                                  | 2.1.9                 | fairylights-2.1.9-1.12.2.jar                     | None                                     |
	| LCH   | fbp                                          | 2.4.1                 | FancyBlockParticles-1.12.x-2.4.1.jar             | None                                     |
	| LCH   | foamfix                                      | 0.10.10-1.12.2        | foamfix-0.10.10-1.12.2.jar                       | None                                     |
	| LCH   | forgelin                                     | 1.8.4                 | Forgelin-1.8.4.jar                               | None                                     |
	| LCH   | galacticraftplanets                          | 4.0.2.244             | Galacticraft-Planets-1.12.2-4.0.2.244.jar        | None                                     |
	| LCH   | ichunutil                                    | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | hats                                         | 7.1.0                 | Hats-1.12.2-7.1.0.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | waila                                        | 1.8.26                | Hwyla-Mod-1.12.2.jar                             | None                                     |
	| LCH   | llibrary                                     | 1.7.19                | llibrary-1.7.19-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire                                   | 1.9.0                 | iceandfire-1.9.0.jar                             | None                                     |
	| LCH   | ido                                          | 1.0.6                 | ido-1.12.2-1.1.0.jar                             | None                                     |
	| LCH   | ironchest                                    | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar                  | None                                     |
	| LCH   | jeiintegration                               | 1.5.1.36              | jeiintegration_1.12.2-1.5.1.36.jar               | None                                     |
	| LCH   | jeivillagers                                 | 1.0                   | jeivillagers-1.12-1.0.2.jar                      | None                                     |
	| LCH   | jepb                                         | 1.2.1                 | jepb-1.12-1.2.1.jar                              | None                                     |
	| LCH   | jeresources                                  | 0.9.2.60              | JustEnoughResources-1.12.2-0.9.2.60.jar          | None                                     |
	| LCH   | librarianlib                                 | 4.20                  | librarianlib-1.12.2-4.20-release.jar             | None                                     |
	| LCH   | lycanitesmobs                                | 2.0.7.2 - MC 1.12.2   | lycanitesmobs-1.12.2-2.0.7.2.jar                 | None                                     |
	| LCH   | malisiscore                                  | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                     | None                                     |
	| LCH   | malisisdoors                                 | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
	| LCH   | mobends                                      | 0.24                  | mobends-0.24_for_MC-1.12.jar                     | None                                     |
	| LCH   | morefurnaces                                 | 1.10.5                | MoreFurnaces-1.12.2-1.10.6.jar                   | None                                     |
	| LCH   | mousetweaks                                  | 2.10                  | MouseTweaks-2.10-mc1.12.2.jar                    | None                                     |
	| LCH   | movingworld                                  | 1.12-6.342            | movingworld-1.12-6.342-full.jar                  | None                                     |
	| LCH   | mowziesmobs                                  | 1.5.4                 | mowziesmobs-1.5.4.jar                            | None                                     |
	| LCH   | multimine                                    | 1.6.1                 | MultiMine-1.12.2.jar                             | None                                     |
	| LCH   | neat                                         | 1.4-17                | Neat+1.4-17.jar                                  | None                                     |
	| LCH   | recipehandler                                | 0.13                  | NoMoreRecipeConflict-0.13(1.12.2).jar            | None                                     |
	| LCH   | openmods                                     | 0.12.2                | OpenModsLib-1.12.2-0.12.2.jar                    | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | openblocks                                   | 1.8.1                 | OpenBlocks-1.12.2-1.8.1.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | orespawn                                     | 3.3.1                 | OreSpawn-1.12-3.3.1.172.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | packingtape                                  | 0.7.6                 | PackingTape-1.12.2-0.7.6.jar                     | None                                     |
	| LCH   | potioncore                                   | 1.8_for_1.12.2        | PotionCore-1.8_for_1.12.2.jar                    | None                                     |
	| LCH   | potionfingers                                | r1.0-8                | PotionFingers-r1.0-8.jar                         | None                                     |
	| LCH   | roguelike                                    | 1.8.0                 | RoguelikeDungeons-1.12.2-1.8.0.jar               | None                                     |
	| LCH   | primal                                       | 0.6.105               | PrimalCore-1.12.2-0.6.105.jar                    | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LCH   | qualitytools                                 | 1.0.7_for_1.12.2      | QualityTools-1.0.7_for_1.12.2.jar                | None                                     |
	| LCH   | additionalstructures                         | 2.3.1                 | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar | None                                     |
	| LCH   | ruins                                        | 17.2                  | Ruins-1.12.2.jar                                 | None                                     |
	| LCH   | silentlib                                    | 3.0.13                | SilentLib-1.12.2-3.0.14+168.jar                  | None                                     |
	| LCH   | scalinghealth                                | 1.3.37                | ScalingHealth-1.12.2-1.3.40+145.jar              | None                                     |
	| LCH   | scarper                                      | 1.1                   | scarper-1.1.jar                                  | None                                     |
	| LCH   | t3s4ebw                                      | 1.0                   | SeedsForWizardry+1.0+For+MC+Forge+1.12.2.jar     | None                                     |
	| LCH   | storagenetwork                               | 1.7.10                | SimpleStorageNetwork-1.12.2-1.7.10.jar           | None                                     |
	| LCH   | lteleporters                                 | 1.12.2-3.0.2          | simpleteleporters-1.12.2-3.0.2.jar               | None                                     |
	| LCH   | spartanweaponry                              | beta 1.3.8            | SpartanWeaponry-1.12.2-beta-1.3.8.jar            | None                                     |
	| LCH   | spartanfire                                  | 0.07                  | spartanfire-0.07.jar                             | None                                     |
	| LCH   | spartanshields                               | 1.5.4                 | SpartanShields-1.12.2-1.5.4.jar                  | None                                     |
	| LCH   | spawnercontrol                               | 1.6.3b                | SpawnerControl-1.6.3b.jar                        | None                                     |
	| LCH   | stepup                                       | 1.0.2-mc1.10-1.12.2   | StepUp-1.0.2-mc1.10-1.12.jar                     | None                                     |
	| LCH   | mo                                           | 1.0                   | sulfur-potassium-1.12-1.1.jar                    | None                                     |
	| LCH   | bspkrscore                                   | at_0.9                | Treecapitator-1.12-at_0.9a.jar                   | None                                     |
	| LCH   | treecapitator                                | at_0.9                | Treecapitator-1.12-at_0.9a.jar                   | None                                     |
	| LCH   | xat                                          | 0.30                  | Trinkets+and+Baubles-0.30.1.jar                  | None                                     |
	| LCH   | twilightforest                               | 3.10.1013             | twilightforest-1.12.2-3.10.1013-universal.jar    | None                                     |
	| LCH   | uteamcore                                    | 2.2.5.147             | u_team_core-1.12.2-2.2.5.147.jar                 | None                                     |
	| LCH   | usefulbackpacks                              | 1.5.1.42              | useful_backpacks-1.12.2-1.5.1.42.jar             | None                                     |
	| LCH   | wailaharvestability                          | 1.1.12                | WailaHarvestability-mc1.12-1.1.12.jar            | None                                     |
	| LCH   | wawla                                        | 2.5.273               | Wawla-1.12.2-2.5.273.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | wolfarmor                                    | 3.4.1.1               | wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar    | None                                     |
	| LCH   | dshuds                                       | 3.6.0.0               | DynamicSurroundingsHuds-1.12.2-3.6.0.0.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | phosphor-lighting                            | 1.12.2-0.2.6          | phosphor-1.12.2-0.2.6+build50-universal.jar      | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCH   | librarianliblate                             | 4.20                  | librarianlib-1.12.2-4.20-release.jar             | None                                     |

	Loaded coremods (and transformers): 
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
  
ItemPatchingLoader (ItemPhysic_Full_1.4.27_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
  
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 451.67' Renderer: 'GeForce GTX 950/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 950/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Builder's Modded Shaders V2.4.1.zip
	OpenGlVersion: 4.6.0 NVIDIA 451.67
	OpenGlRenderer: GeForce GTX 950/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Jennifercutixx** [comment]
Never mind it was bc of an outdated version of block physics :)
