### ISSUE TITLE
Creative core on server

### ISSUE THREAD

**Issue by ghost** [CreativeMD/CreativeCore#84]
Hey ! 

I have a big problem, creative core have a fatal error
The client crash when i join my server (i use vanilla fix for avoid), and the server don't crash

I don't know where this come from.

logs:

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at com.creativemd.creativecore.common.packet.gui.GuiNBTPacket.executeClient(GuiNBTPacket.java:34)
    at com.creativemd.creativecore.common.packet.PacketReciever$1.run(PacketReciever.java:86)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 9 more

help please :(

**Comment by Chocodu31** [comment]
Sorry i can't help you

,_,

**Comment by CreativeMD** [comment]
Make sure to update CreativeCore that should fix your issue.

**Comment by ghost** [comment]
Man, i have the last update...

**Comment by CreativeMD** [comment]
https://cdn.discordapp.com/attachments/326729168266199040/748915793831657502/CreativeCore_v1.10.18_mc1.12.2.jar
https://cdn.discordapp.com/attachments/326729168266199040/748915823812280422/LittleTiles_v1.5.0-pre199_41_mc1.12.2.jar
https://cdn.discordapp.com/attachments/326729168266199040/745705002861068319/OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar

There is a new unofficial version which will be released soon. Maybe that fixes your issue. If not make sure to post the entire crash-report that would make my life a lot easier.
