### ISSUE TITLE
IllegalArgumentException: Stack can not be invalid

### ISSUE THREAD

**Issue by ken1882** [CreativeMD/CreativeCore#86]
This bug will randomly occur when I mining near the lava, IDK this bug is due to item physics or the core itself, but I'll post here.

```
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2020-08-17 17:14:16 CST
Description: Unexpected error

java.lang.IllegalArgumentException: Stack can not be invalid!
    at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:504)
    at com.creativemd.creativecore.common.utils.stack.InfoOre.isStackInstanceIgnoreSize(InfoOre.java:64)
    at com.creativemd.creativecore.common.utils.stack.InfoStack.isInstanceIgnoreSize(InfoStack.java:334)
    at com.creativemd.creativecore.common.utils.type.SortingList.canBeFoundInList(SortingList.java:167)
    at com.creativemd.creativecore.common.utils.type.SortingList.canPass(SortingList.java:188)
    at com.creativemd.itemphysic.physics.ServerPhysic.isItemBurning(ServerPhysic.java:215)
    at net.minecraft.entity.item.EntityItem.isBurning(EntityItem.java)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:383)
    at net.minecraft.client.renderer.RenderGlobal.redirect$zbh000$renderEntityStatic(RenderGlobal.java:3727)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:839)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1800)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1613)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1384)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by CreativeMD** [comment]
Fixed in the newest version of CreativeCore. Sorry that it took me so long to fix it. Thanks for reporting this issue!

**Comment by ken1882** [comment]
@CreativeMD I didn't listed the steps to reproduce so it's ok. Anyway thanks for the fix!

**Comment by CreativeMD** [comment]
That was not the problem, I was just too busy with other things.
