### ISSUE TITLE
error server

### ISSUE THREAD

**Issue by moises7u7** [CreativeMD/CreativeCore#88]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_41_mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.18_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 8/29/20 7:00 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.instantiate(SimpleNetworkWrapper.java:166)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.registerMessage(SimpleNetworkWrapper.java:159)
	at net.infstudio.goki.common.network.GokiPacketHandler.<clinit>(GokiPacketHandler.java:22)
	at net.infstudio.goki.common.handlers.CommonHandler.playerLoggedIn(CommonHandler.java:126)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_208_CommonHandler_playerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 23 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@5a5c128 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 25 more
Caused by: java.lang.RuntimeException: Attempted to load class bud for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.19-ovh-xxxx-std-ipv6-64
	Java Version: 1.8.0_252, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 10647367344 bytes (10154 MB) / 12287737856 bytes (11718 MB) up to 12287737856 bytes (11718 MB)
	JVM Flags: 4 total; -Xmx12228M -Xms12228M -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=512M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version        | Source                                      | Signature                                |
	|:------ |:----------------- |:-------------- |:------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2         | minecraft.jar                               | None                                     |
	| LCHIJA | mcp               | 9.42           | minecraft.jar                               | None                                     |
	| LCHIJA | FML               | 8.0.99.99      | forge-1.12.2.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854   | forge-1.12.2.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy | 1.0.0          | minecraft.jar                               | None                                     |
	| LCHIJA | littletilescore   | 1.0.0          | minecraft.jar                               | None                                     |
	| LCHIJA | securitycraft     | v1.8.19.1      | [1.12.2]+SecurityCraft+v1.8.19.1.jar        | None                                     |
	| LCHIJA | carryon           | 1.12.3         | carryon-1.12.2-1.12.3.15.jar                | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHIJA | classiccombat     | 1.0.1          | ClassicCombat-1.0.1 (1).jar                 | None                                     |
	| LCHIJA | comforts          | 1.4.1.2        | comforts-1.12.2-1.4.1.2.jar                 | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | opframe           | 1.4.0          | OnlinePicFrame_v1.5.0-pre1_mc1.12.2 (1).jar | None                                     |
	| LCHIJA | creativecore      | 1.10.0         | CreativeCore_v1.10.18_mc1.12.2.jar          | None                                     |
	| LCHIJA | customnpcs        | 1.12           | CustomNPCs_1.12.2-(05Jul20).jar             | None                                     |
	| LCHIJA | fastleafdecay     | v14            | FastLeafDecay-v14.jar                       | None                                     |
	| LCHIJA | fencejumper       | 1.0.5          | fencejumper-1.12-1.0.5.jar                  | None                                     |
	| LCHIJA | wumpleutil        | 2.12.6         | wumpleutil-1.12.2-2.12.6.jar                | 1e57901a90acd4a3a54295b6decff5397be51a31 |
	| LCHIJA | foodfunk          | 4.9.6          | foodfunk-1.12.2-4.9.6.jar                   | None                                     |
	| LCHIJA | gokistats         | 1.2.7.2        | gokiStats-1.2.7.2.jar                       | None                                     |
	| LCHIJA | hidenames         | 1.4.1          | HideNames-1.12.2-1.4.1.jar                  | None                                     |
	| LCHIJA | improvedbackpacks | 1.12.2-1.4.0.0 | ImprovedBackpacks-1.12.2-1.4.0.0 (1).jar    | None                                     |
	| LCHIJA | ironfurnaces      | 1.3.5          | ironfurnaces-1.3.5.jar                      | None                                     |
	| LCHIJA | jei               | 4.15.0.291     | jei_1.12.2-4.15.0.291.jar                   | None                                     |
	| LCHIJA | littletiles       | 1.5.0          | LittleTiles_v1.5.0-pre199_41_mc1.12.2.jar   | None                                     |
	| LCHIJA | radixcore         | 1.12.x-2.2.1   | RadixCore-1.12.2.jar                        | None                                     |
	| LCHIJA | mca               | 1.12.2-5.3.1   | MCA-1.12.x-5.3.1-universal.jar              | None                                     |
	| LCHIJA | powerdrop         | MC1.12.2-1.1.2 | PowerDrop-MC1.12.2-1.1.2.jar                | None                                     |
	| LCHIJA | reap              | 1.5.2          | reap-1.5.2.jar                              | None                                     |
	| LCHIJA | tombstone         | 3.6.5          | tombstone-3.6.5-1.12.2.jar                  | None                                     |

	Loaded coremods (and transformers): 
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_41_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore_v1.10.18_mc1.12.2.jar)
  
	Profiler Position: N/A (disabled)
	Player Count: 1 / 144; [EntityPlayerMP['moises7u7'/510, l='Decaland', x=107.50, y=61.00, z=550.50]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by CreativeMD** [comment]
Should be fixed in newer pre-releases.
